from __future__ import annotations

# ruff: noqa: E402
import argparse
import json
import math
import random
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from SafeLens.core.base import PipelineConfig
from SafeLens.nla import list_nla_profiles
from SafeLens.utils import HuggingFaceModelWrapper, build_model_wrapper

DEFAULT_MODEL = "sshleifer/tiny-gpt2"
DEFAULT_PROMPT = (
    "User: Compare a benign safety explanation with a jailbreak strategy and "
    "explain which tokens trigger the monitor."
)
DEFAULT_OUTPUT = ROOT / "apps/local_explorer/src/realRunData.ts"
DEFAULT_ARTIFACT_OUTPUT = ROOT / "outputs/local-explorer/real-run.explorer.json"
RISK_TERMS = ("jail", "break", "strategy", "trigger", "monitor", "policy")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a small Local Explorer dataset from a real SafeLens model flow."
    )
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--prompt", default=DEFAULT_PROMPT)
    parser.add_argument("--cache-dir", default=".cache/safelens/local-explorer-real-flow")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--artifact-output", type=Path, default=DEFAULT_ARTIFACT_OUTPUT)
    parser.add_argument("--run-id", default="real-hf-tiny-gpt2-local-explorer")
    parser.add_argument("--sample-id", default="real-forward-cache-001")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--max-new-tokens", type=int, default=3)
    parser.add_argument("--temperature", type=float, default=0.0)
    args = parser.parse_args()

    wrapper = _load_wrapper(args.model, args.cache_dir)
    try:
        run = _build_run(
            wrapper,
            prompt=args.prompt,
            run_id=args.run_id,
            sample_id=args.sample_id,
            seed=args.seed,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
        )
    finally:
        wrapper.remove_hooks()

    output_path = args.output if args.output.is_absolute() else ROOT / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(run, indent=2)
    output_path.write_text(
        'import type { ExplorerRun } from "./types";\n\n'
        "// Generated by scripts/build_local_explorer_real_run.py from a real model forward pass.\n"
        f"export const realRun = {payload} satisfies ExplorerRun;\n",
        encoding="utf-8",
    )
    artifact_path = (
        args.artifact_output if args.artifact_output.is_absolute() else ROOT / args.artifact_output
    )
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    artifact_path.write_text(
        json.dumps(
            {
                "schema_version": "1.0",
                "run": {
                    "run_id": run["runId"],
                    "model_name": run["modelName"],
                    "model_source": run["modelSource"],
                },
                "samples": [run],
                "metrics": sorted(run["metricProvenance"]),
                "artifacts": {"embedded": True},
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"wrote {_display_path(output_path)}")
    print(f"wrote {_display_path(artifact_path)}")
    print(
        json.dumps(
            {
                "model": run["modelName"],
                "tokens": len(run["tokens"]),
                "layers": run["layers"],
                "attention_heads": [head["id"] for head in run["attentionHeads"]],
                "mlp_neurons": [neuron["id"] for neuron in run["mlpNeurons"]],
                "nla_status": run["nla"][0].get("status") if run["nla"] else "missing",
            },
            indent=2,
        )
    )


def _display_path(path: Path) -> Path:
    try:
        return path.relative_to(ROOT)
    except ValueError:
        return path


def _load_wrapper(model_id: str, cache_dir: str) -> HuggingFaceModelWrapper:
    config = PipelineConfig.model_validate(
        {
            "model": {
                "source": "huggingface",
                "name": model_id,
                "device": "cpu",
                "dtype": "float32",
                "cache_dir": cache_dir,
                "load_kwargs": {"low_cpu_mem_usage": False},
            }
        }
    )
    wrapper = build_model_wrapper(config.model)
    if not isinstance(wrapper, HuggingFaceModelWrapper):
        raise TypeError(f"expected HuggingFaceModelWrapper, got {type(wrapper).__name__}")
    wrapper.load_model()
    return wrapper


def _build_run(
    wrapper: HuggingFaceModelWrapper,
    *,
    prompt: str,
    run_id: str = "real-hf-tiny-gpt2-local-explorer",
    sample_id: str = "real-forward-cache-001",
    seed: int = 0,
    max_new_tokens: int = 3,
    temperature: float = 0.0,
) -> dict[str, Any]:
    torch = _require_torch()
    random.seed(seed)
    torch.manual_seed(seed)
    tokens = wrapper.to_tokens(prompt, prepend_bos=False)
    token_ids = [int(item) for item in tokens[0].detach().cpu().tolist()]
    token_texts = [str(item) for item in wrapper.to_str_tokens(tokens, prepend_bos=False)]
    n_layers = int(wrapper.cfg.n_layers or 1)
    layers = list(range(n_layers))
    cache_layers = _cache_layers(layers)
    output, cache = wrapper.run_with_cache({"input_ids": tokens}, layers=cache_layers)

    residual_keys = [f"layer_{layer}.resid_post" for layer in layers]
    final_resid = cache[residual_keys[-1]][0].float()
    target_token_id = _target_token_id(wrapper)
    target_direction = wrapper.tokens_to_residual_directions(target_token_id).float()
    target_direction = target_direction / target_direction.norm().clamp_min(1e-12)

    risk_scores_raw = (final_resid @ target_direction).detach().cpu().tolist()
    risk_scores = _normalize(risk_scores_raw)
    attention_track = _final_token_attention_track(cache, layers)
    residual_alignment = _normalize(risk_scores_raw)
    risk_indices = _risk_indices(token_texts)
    selected_indices = risk_indices[:3] or _top_indices(risk_scores, 3)

    residual_norms_by_layer = {
        layer: cache[f"layer_{layer}.resid_post"][0].float().norm(dim=-1).detach().cpu().tolist()
        for layer in layers
    }
    projection_by_layer = {
        layer: (cache[f"layer_{layer}.resid_post"][0].float() @ target_direction)
        .detach()
        .cpu()
        .tolist()
        for layer in layers
    }
    projection_values = [value for values in projection_by_layer.values() for value in values]
    norm_values = [value for values in residual_norms_by_layer.values() for value in values]
    projection_minmax = _minmax(projection_values)
    norm_minmax = _minmax(norm_values)

    generation_kwargs: dict[str, Any] = {
        "max_new_tokens": max_new_tokens,
        "do_sample": temperature > 0,
        "pad_token_id": wrapper.tokenizer.eos_token_id,
    }
    if temperature > 0:
        generation_kwargs["temperature"] = temperature
    generated = wrapper.generate(prompt, **generation_kwargs)
    top_token_id = int(output.logits[0, -1].argmax().detach().cpu().item())
    top_token = wrapper.to_single_str_token(top_token_id)
    logit_lens = _logit_lens_rows(
        wrapper,
        cache,
        layers,
        token_ids,
        final_next_token_id=top_token_id,
    )

    return {
        "runId": run_id,
        "modelName": wrapper.name,
        "modelSource": "huggingface",
        "sampleId": sample_id,
        "prompt": prompt,
        "tokens": [
            {
                "index": index,
                "text": text,
                "tokenId": token_ids[index],
                "source": "prompt",
                "isSpecial": token_ids[index] in wrapper.tokenizer.all_special_ids,
                "risk": _round_score(risk_scores[index]),
                "attribution": _round_score(attention_track[index]),
            }
            for index, text in enumerate(token_texts)
        ],
        "layers": layers,
        "nla": _nla_status_rows(
            wrapper=wrapper,
            token_texts=token_texts,
            token_indices=selected_indices,
            final_layer=layers[-1],
            final_norms=residual_norms_by_layer[layers[-1]],
        ),
        "nlaCompatibility": _nla_compatibility(wrapper, layers),
        "attentionHeads": _attention_heads(cache, layers, token_texts, risk_indices),
        "mlpNeurons": _mlp_neurons(cache, layers),
        "residualCells": [
            {
                "layer": layer,
                "tokenIndex": token_index,
                "norm": round(float(residual_norms_by_layer[layer][token_index]), 3),
                "rawDirection": round(float(projection_by_layer[layer][token_index]), 6),
                "riskDirection": _round_score(
                    _normalize_one(
                        float(projection_by_layer[layer][token_index]),
                        projection_minmax,
                    )
                ),
                "semanticDensity": _round_score(
                    _normalize_one(float(residual_norms_by_layer[layer][token_index]), norm_minmax)
                ),
            }
            for layer in layers
            for token_index in range(len(token_texts))
        ],
        "logitLens": logit_lens,
        "attentionCells": _attention_cells(cache, layers),
        "mlpCells": _mlp_cells(cache, layers),
        "attributionTracks": [
            {"name": "Final-token attention", "values": [_round_score(v) for v in attention_track]},
            {
                "name": "Residual direction alignment",
                "values": [_round_score(v) for v in residual_alignment],
            },
            {"name": "Token safety proxy", "values": [_round_score(v) for v in risk_scores]},
        ],
        "attributionMethods": _attribution_methods(
            layers=layers,
            projection_by_layer=projection_by_layer,
            attention_track=attention_track,
            risk_scores=risk_scores,
        ),
        "metricProvenance": {
            "tokenRisk": {
                "label": "Safety-token direction proxy",
                "method": (
                    "residual projection onto the selected safety-token unembedding direction"
                ),
                "semantics": (
                    "Relative alignment within this run; not a calibrated safety probability."
                ),
                "normalization": "min-max over final-layer token projections",
                "kind": "derived_proxy",
            },
            "tokenAttribution": {
                "label": "Final-token attention proxy",
                "method": "mean final-query attention over all cached layers and heads",
                "semantics": "Attention mass is descriptive and is not causal attribution.",
                "normalization": "min-max over source-token attention values",
                "kind": "derived_proxy",
            },
            "residualHeatmap": {
                "label": "Residual direction alignment",
                "method": "resid_post projection onto the selected safety-token direction",
                "semantics": "Layer-token directional alignment relative to this run.",
                "normalization": "min-max over all layer-token projections",
                "kind": "derived_proxy",
            },
            "attentionHeatmap": {
                "label": "Attention concentration",
                "method": "mean across heads of the maximum source attention for each query token",
                "semantics": "How concentrated attention is; it is not a risk score.",
                "normalization": "none; attention probabilities are already bounded",
                "kind": "raw",
            },
            "mlpHeatmap": {
                "label": "Mean absolute MLP activation",
                "method": "mean absolute hook_post activation across neurons",
                "semantics": (
                    "Relative activation magnitude; it is not neuron-level causal influence."
                ),
                "normalization": "min-max over all layer-token means",
                "kind": "derived_proxy",
            },
            "mlpNeuronActivation": {
                "label": "Signed MLP post activation",
                "method": "direct value from the selected hook_post neuron and token",
                "semantics": (
                    "Neuron response with sign preserved; not target-logit contribution, "
                    "probe contribution, or causal ablation effect."
                ),
                "normalization": "raw, absolute raw, or max-absolute display normalization",
                "kind": "raw",
            },
        },
        "metadata": {
            "realFlow": True,
            "generatedContinuation": generated,
            "nextToken": top_token,
            "nextTokenId": top_token_id,
            "riskDirectionTokenId": target_token_id,
            "riskDirectionToken": wrapper.to_single_str_token(target_token_id),
            "nlaProfiles": list_nla_profiles(),
            "generation": {
                "seed": seed,
                "maxNewTokens": max_new_tokens,
                "temperature": temperature,
                "doSample": temperature > 0,
            },
        },
    }


def _cache_layers(layers: list[int]) -> list[str]:
    names: list[str] = []
    for layer in layers:
        names.extend(
            [
                f"layer_{layer}.resid_pre",
                f"layer_{layer}.resid_mid",
                f"layer_{layer}.resid_post",
                f"layer_{layer}.attn_out",
                f"layer_{layer}.mlp_out",
                f"layer_{layer}.post",
                f"layer_{layer}.result",
                f"blocks.{layer}.attn.hook_pattern",
            ]
        )
    return names


def _logit_lens_rows(
    wrapper: HuggingFaceModelWrapper,
    cache: dict[str, Any],
    layers: list[int],
    token_ids: list[int],
    *,
    final_next_token_id: int,
    top_k: int = 5,
) -> list[dict[str, Any]]:
    """Project each cached resid_post through final norm and the real unembedding."""
    torch = _require_torch()
    unembed = wrapper.W_U.detach().float()
    bias = wrapper.b_U.detach().float()
    final_norm = _final_norm_module(wrapper)
    rows: list[dict[str, Any]] = []

    with torch.no_grad():
        for layer in layers:
            residual = cache[f"layer_{layer}.resid_post"][0].float()
            normalized = final_norm(residual) if final_norm is not None else residual
            if isinstance(normalized, tuple):
                normalized = normalized[0]
            layer_unembed = unembed.to(device=normalized.device, dtype=normalized.dtype)
            layer_bias = bias.to(device=normalized.device, dtype=normalized.dtype)
            logits = normalized @ layer_unembed + layer_bias
            probabilities = torch.softmax(logits, dim=-1)
            count = min(top_k, int(logits.shape[-1]))
            top_logits, top_ids = torch.topk(logits, k=count, dim=-1)

            for token_index in range(len(token_ids)):
                target_id = (
                    token_ids[token_index + 1]
                    if token_index + 1 < len(token_ids)
                    else final_next_token_id
                )
                token_logits = logits[token_index]
                target_logit = token_logits[target_id]
                target_rank = int((token_logits > target_logit).sum().detach().cpu().item()) + 1
                predictions = []
                for rank_index in range(count):
                    predicted_id = int(top_ids[token_index, rank_index].detach().cpu().item())
                    predictions.append(
                        {
                            "tokenId": predicted_id,
                            "tokenText": wrapper.to_single_str_token(predicted_id),
                            "logit": round(
                                float(top_logits[token_index, rank_index].detach().cpu().item()),
                                6,
                            ),
                            "probability": round(
                                float(
                                    probabilities[token_index, predicted_id].detach().cpu().item()
                                ),
                                8,
                            ),
                        }
                    )
                rows.append(
                    {
                        "layer": layer,
                        "tokenIndex": token_index,
                        "targetTokenId": target_id,
                        "targetTokenText": wrapper.to_single_str_token(target_id),
                        "targetLogit": round(float(target_logit.detach().cpu().item()), 6),
                        "targetProbability": round(
                            float(probabilities[token_index, target_id].detach().cpu().item()),
                            8,
                        ),
                        "targetRank": target_rank,
                        "topPredictions": predictions,
                        "sourceKey": f"layer_{layer}.resid_post -> ln_final -> unembed",
                    }
                )
    return rows


def _final_norm_module(wrapper: HuggingFaceModelWrapper) -> Any | None:
    model = getattr(wrapper, "model", None)
    if model is None:
        return None
    for path in (
        "transformer.ln_f",
        "model.norm",
        "model.final_layernorm",
        "model.final_layer_norm",
        "gpt_neox.final_layer_norm",
        "decoder.final_layer_norm",
        "norm",
        "ln_f",
    ):
        current = model
        for part in path.split("."):
            current = getattr(current, part, None)
            if current is None:
                break
        if current is not None and callable(current):
            return current
    return None


def _target_token_id(wrapper: HuggingFaceModelWrapper) -> int:
    for text in (" jailbreak", " unsafe", " policy", " monitor", " safety"):
        ids = wrapper.to_tokens(text, prepend_bos=False)
        if getattr(ids, "numel", lambda: 0)() > 0:
            return int(ids[0, -1].detach().cpu().item())
    return int(wrapper.tokenizer.eos_token_id)


def _risk_indices(token_texts: list[str]) -> list[int]:
    indices: list[int] = []
    for index, text in enumerate(token_texts):
        lowered = text.strip().lower()
        if any(term in lowered for term in RISK_TERMS):
            indices.append(index)
    return indices


def _final_token_attention_track(cache: dict[str, Any], layers: list[int]) -> list[float]:
    rows = []
    for layer in layers:
        pattern = cache[f"blocks.{layer}.attn.hook_pattern"][0].float()
        rows.append(pattern[:, -1, :].mean(dim=0))
    if not rows:
        return []
    mean_row = _require_torch().stack(rows).mean(dim=0).detach().cpu().tolist()
    return _normalize(mean_row)


def _attribution_methods(
    *,
    layers: list[int],
    projection_by_layer: dict[int, list[float]],
    attention_track: list[float],
    risk_scores: list[float],
) -> list[dict[str, Any]]:
    return [
        {
            "id": "residual_direction",
            "label": "Residual direction projection",
            "description": (
                "Signed resid_post projection onto the selected safety-token unembedding direction."
            ),
            "evidenceKind": "derived_proxy",
            "signed": True,
            "normalization": "raw projection or max-absolute display normalization",
            "available": True,
            "rows": [
                {
                    "layer": layer,
                    "label": f"L{layer}",
                    "values": [round(float(value), 6) for value in projection_by_layer[layer]],
                    "sourceKey": f"layer_{layer}.resid_post -> safety token direction",
                }
                for layer in layers
            ],
        },
        {
            "id": "final_attention_proxy",
            "label": "Final-token attention proxy",
            "description": (
                "Mean final-query attention across cached layers and heads; "
                "descriptive and non-causal."
            ),
            "evidenceKind": "derived_proxy",
            "signed": False,
            "normalization": "min-max over source-token attention values",
            "available": True,
            "rows": [
                {
                    "layer": -1,
                    "label": "Mean",
                    "values": [_round_score(value) for value in attention_track],
                    "sourceKey": "all blocks.attn.hook_pattern[:, final_query, :]",
                }
            ],
        },
        {
            "id": "token_safety_proxy",
            "label": "Token safety proxy",
            "description": ("Final-layer residual-direction alignment normalized within this run."),
            "evidenceKind": "derived_proxy",
            "signed": False,
            "normalization": "min-max over final-layer token projections",
            "available": True,
            "rows": [
                {
                    "layer": layers[-1],
                    "label": f"L{layers[-1]}",
                    "values": [_round_score(value) for value in risk_scores],
                    "sourceKey": f"layer_{layers[-1]}.resid_post -> normalized safety proxy",
                }
            ],
        },
        {
            "id": "integrated_gradients",
            "label": "Integrated Gradients",
            "description": "Signed input attribution against a user-selected target objective.",
            "evidenceKind": "causal",
            "signed": True,
            "normalization": "not available",
            "available": False,
            "unavailableReason": (
                "No Captum attribution job is stored in this run. Run the attribution "
                "backend job with a target objective before using this method."
            ),
            "rows": [],
        },
    ]


def _attention_heads(
    cache: dict[str, Any],
    layers: list[int],
    token_texts: list[str],
    risk_indices: list[int],
) -> list[dict[str, Any]]:
    candidates: list[dict[str, Any]] = []
    risk_positions = risk_indices or [len(token_texts) - 1]
    for layer in layers:
        pattern = cache[f"blocks.{layer}.attn.hook_pattern"][0].float()
        for head in range(int(pattern.shape[0])):
            head_pattern = pattern[head]
            final_row = head_pattern[-1]
            risk_mass = float(final_row[risk_positions].sum().detach().cpu().item())
            entropy = _entropy(final_row.detach().cpu().tolist())
            candidates.append(
                {
                    "id": f"L{layer}H{head}",
                    "layer": layer,
                    "head": head,
                    "role": "real attention pattern",
                    "riskContribution": _round_score(risk_mass),
                    "entropy": round(entropy, 3),
                    "distributionByToken": [
                        [_round_score(float(value)) for value in row.detach().cpu().tolist()]
                        for row in head_pattern
                    ],
                }
            )
    selected: list[dict[str, Any]] = []
    for layer in layers:
        layer_candidates = [item for item in candidates if item["layer"] == layer]
        layer_candidates.sort(key=lambda item: item["riskContribution"], reverse=True)
        selected.extend(layer_candidates[:3])
    return selected


def _attention_cells(cache: dict[str, Any], layers: list[int]) -> list[dict[str, Any]]:
    cells: list[dict[str, Any]] = []
    for layer in layers:
        source_key = f"blocks.{layer}.attn.hook_pattern"
        pattern = cache[source_key][0].float()
        concentration = pattern.max(dim=-1).values.mean(dim=0).detach().cpu().tolist()
        for token_index, value in enumerate(concentration):
            cells.append(
                {
                    "layer": layer,
                    "tokenIndex": token_index,
                    "value": _round_score(float(value)),
                    "rawValue": round(float(value), 6),
                    "metric": "mean_head_max_source_attention",
                    "sourceKey": source_key,
                }
            )
    return cells


def _mlp_neurons(cache: dict[str, Any], layers: list[int]) -> list[dict[str, Any]]:
    candidates: list[dict[str, Any]] = []
    for layer in layers:
        signed_post = cache[f"layer_{layer}.post"][0].float()
        post = signed_post.abs()
        if post.ndim != 2:
            continue
        per_neuron = post.max(dim=0).values.detach().cpu().tolist()
        scale = max(per_neuron) if per_neuron else 1.0
        for neuron, value in enumerate(per_neuron):
            token_scores = post[:, neuron].detach().cpu().tolist()
            signed_token_scores = signed_post[:, neuron].detach().cpu().tolist()
            top_tokens = _top_indices(token_scores, 3)
            positive_top_tokens = sorted(
                range(len(signed_token_scores)),
                key=lambda index: signed_token_scores[index],
                reverse=True,
            )[:3]
            negative_top_tokens = sorted(
                range(len(signed_token_scores)),
                key=lambda index: signed_token_scores[index],
            )[:3]
            candidates.append(
                {
                    "id": f"L{layer}N{neuron:04d}",
                    "layer": layer,
                    "neuron": neuron,
                    "label": "real MLP post neuron",
                    "activation": _round_score(float(value) / max(scale, 1e-12)),
                    "riskContribution": _round_score(
                        sum(token_scores[index] for index in top_tokens)
                        / max(sum(token_scores), 1e-12)
                    ),
                    "topTokens": top_tokens,
                    "positiveTopTokens": positive_top_tokens,
                    "negativeTopTokens": negative_top_tokens,
                    "activationsByToken": [
                        round(float(activation), 6) for activation in signed_token_scores
                    ],
                    "maxAbsoluteActivation": round(float(value), 6),
                }
            )
    selected: list[dict[str, Any]] = []
    for layer in layers:
        layer_candidates = [item for item in candidates if item["layer"] == layer]
        layer_candidates.sort(key=lambda item: item["activation"], reverse=True)
        selected.extend(layer_candidates[:16])
    return selected


def _mlp_cells(cache: dict[str, Any], layers: list[int]) -> list[dict[str, Any]]:
    raw_cells: list[tuple[int, int, float, str]] = []
    for layer in layers:
        source_key = f"layer_{layer}.post"
        post = cache[source_key][0].float().abs()
        if post.ndim != 2:
            continue
        token_means = post.mean(dim=-1).detach().cpu().tolist()
        raw_cells.extend(
            (layer, token_index, float(value), source_key)
            for token_index, value in enumerate(token_means)
        )
    bounds = _minmax([value for _layer, _token, value, _key in raw_cells])
    return [
        {
            "layer": layer,
            "tokenIndex": token_index,
            "value": _round_score(_normalize_one(value, bounds)),
            "rawValue": round(value, 6),
            "metric": "mean_absolute_mlp_post_activation",
            "sourceKey": source_key,
        }
        for layer, token_index, value, source_key in raw_cells
    ]


def _nla_status_rows(
    *,
    wrapper: HuggingFaceModelWrapper,
    token_texts: list[str],
    token_indices: list[int],
    final_layer: int,
    final_norms: list[float],
) -> list[dict[str, Any]]:
    profiles = list_nla_profiles()
    profile_names = ", ".join(profile["name"] for profile in profiles)
    message = (
        f"Real activation captured from {wrapper.name}, but no registered NLA profile "
        f"matches this smoke-test model/d_model={wrapper.cfg.d_model}. Supported profiles: "
        f"{profile_names}. Run a matching Qwen/Gemma profile to produce an AV/AR explanation."
    )
    components = ("resid_post", "attn_result", "mlp_out")
    return [
        {
            "tokenIndex": int(token_index),
            "layer": int(final_layer),
            "component": components[row_index % len(components)],
            "explanation": message,
            "cosine": 0.0,
            "mse": 0.0,
            "activationNorm": round(float(final_norms[token_index]), 3),
            "status": "unavailable",
            "profile": None,
            "source": "real_model_cache",
            "token": token_texts[token_index],
        }
        for row_index, token_index in enumerate(token_indices)
    ]


def _nla_compatibility(
    wrapper: HuggingFaceModelWrapper,
    layers: list[int],
) -> dict[str, Any]:
    profiles = list_nla_profiles()
    model_name = str(wrapper.name)
    d_model = int(wrapper.cfg.d_model or 0)
    rows: list[dict[str, Any]] = []
    for profile in profiles:
        base_model = str(profile["base_model"])
        profile_layer = int(profile["layer"])
        profile_d_model = int(profile["d_model"])
        model_matches = model_name.lower() == base_model.lower()
        layer_available = profile_layer in layers
        d_model_matches = profile_d_model == d_model
        structurally_compatible = model_matches and layer_available and d_model_matches
        status = "artifact_missing" if structurally_compatible else "incompatible"
        failures = []
        if not model_matches:
            failures.append(f"model requires {base_model}")
        if not layer_available:
            failures.append(f"layer L{profile_layer} is not cached")
        if not d_model_matches:
            failures.append(f"d_model requires {profile_d_model}, run has {d_model}")
        reason = (
            "Profile structure matches; AV/AR result artifact has not been generated."
            if structurally_compatible
            else "; ".join(failures)
        )
        rows.append(
            {
                "name": str(profile["name"]),
                "baseModel": base_model,
                "layer": profile_layer,
                "component": str(profile["component"]),
                "dModel": profile_d_model,
                "modelMatches": model_matches,
                "layerAvailable": layer_available,
                "dModelMatches": d_model_matches,
                "status": status,
                "reason": reason,
            }
        )
    return {
        "modelName": model_name,
        "dModel": d_model,
        "availableLayers": layers,
        "profiles": rows,
    }


def _normalize(values: list[float]) -> list[float]:
    bounds = _minmax(values)
    return [_normalize_one(value, bounds) for value in values]


def _normalize_one(value: float, bounds: tuple[float, float]) -> float:
    lo, hi = bounds
    if math.isclose(lo, hi, rel_tol=0.0, abs_tol=1e-12):
        return 0.0
    return max(0.0, min(1.0, (value - lo) / (hi - lo)))


def _minmax(values: list[float]) -> tuple[float, float]:
    if not values:
        return (0.0, 1.0)
    return (float(min(values)), float(max(values)))


def _round_score(value: float) -> float:
    return round(max(0.0, min(1.0, float(value))), 3)


def _top_indices(values: list[float], count: int) -> list[int]:
    return [
        index
        for index, _value in sorted(
            enumerate(values),
            key=lambda item: abs(float(item[1])),
            reverse=True,
        )[:count]
    ]


def _entropy(values: list[float]) -> float:
    total = sum(max(0.0, value) for value in values)
    if total <= 0:
        return 0.0
    entropy = 0.0
    for value in values:
        probability = max(0.0, value) / total
        if probability > 0:
            entropy -= probability * math.log(probability)
    return entropy


def _require_torch() -> Any:
    import torch

    return torch


if __name__ == "__main__":
    main()
