"""TransformerLens model coverage metadata.

The official names below mirror TransformerLens' legacy `supported_models.py`
list consulted on 2026-06-02. SafeLens also carries a small set of
TransformerBridge-style architecture aliases where modern TransformerLens
support is architecture-based rather than a fixed checkpoint list. Runtime
loading stays inside SafeLens' own Transformers-based wrappers; this module is
a compatibility target, not a dependency bridge.
"""

from __future__ import annotations

TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES: tuple[str, ...] = (
    "01-ai/Yi-34B",
    "01-ai/Yi-34B-Chat",
    "01-ai/Yi-6B",
    "01-ai/Yi-6B-Chat",
    "ai-forever/mGPT",
    "allenai/OLMo-1B-hf",
    "allenai/OLMo-2-0425-1B",
    "allenai/OLMo-2-1124-7B",
    "allenai/Olmo-3-32B-Think",
    "allenai/Olmo-3-7B-Instruct",
    "allenai/Olmo-3-7B-Think",
    "allenai/Olmo-3.1-32B-Instruct",
    "allenai/Olmo-3.1-32B-Think",
    "allenai/OLMo-7B-hf",
    "allenai/OLMoE-1B-7B-0924",
    "ArthurConmy/redwood_attn_2l",
    "Baidicoot/Othello-GPT-Transformer-Lens",
    "bigcode/santacoder",
    "bigscience/bloom-1b1",
    "bigscience/bloom-1b7",
    "bigscience/bloom-3b",
    "bigscience/bloom-560m",
    "bigscience/bloom-7b1",
    "codellama/CodeLlama-7b-hf",
    "codellama/CodeLlama-7b-Instruct-hf",
    "codellama/CodeLlama-7b-Python-hf",
    "distilgpt2",
    "EleutherAI/gpt-j-6B",
    "EleutherAI/gpt-neo-1.3B",
    "EleutherAI/gpt-neo-125M",
    "EleutherAI/gpt-neo-2.7B",
    "EleutherAI/gpt-neox-20b",
    "EleutherAI/pythia-1.4b",
    "EleutherAI/pythia-1.4b-deduped",
    "EleutherAI/pythia-1.4b-deduped-v0",
    "EleutherAI/pythia-1.4b-v0",
    "EleutherAI/pythia-12b",
    "EleutherAI/pythia-12b-deduped",
    "EleutherAI/pythia-12b-deduped-v0",
    "EleutherAI/pythia-12b-v0",
    "EleutherAI/pythia-14m",
    "EleutherAI/pythia-160m",
    "EleutherAI/pythia-160m-deduped",
    "EleutherAI/pythia-160m-deduped-v0",
    "EleutherAI/pythia-160m-seed1",
    "EleutherAI/pythia-160m-seed2",
    "EleutherAI/pythia-160m-seed3",
    "EleutherAI/pythia-160m-v0",
    "EleutherAI/pythia-1b",
    "EleutherAI/pythia-1b-deduped",
    "EleutherAI/pythia-1b-deduped-v0",
    "EleutherAI/pythia-1b-v0",
    "EleutherAI/pythia-2.8b",
    "EleutherAI/pythia-2.8b-deduped",
    "EleutherAI/pythia-2.8b-deduped-v0",
    "EleutherAI/pythia-2.8b-v0",
    "EleutherAI/pythia-31m",
    "EleutherAI/pythia-410m",
    "EleutherAI/pythia-410m-deduped",
    "EleutherAI/pythia-410m-deduped-v0",
    "EleutherAI/pythia-410m-v0",
    "EleutherAI/pythia-6.9b",
    "EleutherAI/pythia-6.9b-deduped",
    "EleutherAI/pythia-6.9b-deduped-v0",
    "EleutherAI/pythia-6.9b-v0",
    "EleutherAI/pythia-70m",
    "EleutherAI/pythia-70m-deduped",
    "EleutherAI/pythia-70m-deduped-v0",
    "EleutherAI/pythia-70m-v0",
    "facebook/hubert-base-ls960",
    "facebook/opt-1.3b",
    "facebook/opt-125m",
    "facebook/opt-13b",
    "facebook/opt-2.7b",
    "facebook/opt-30b",
    "facebook/opt-6.7b",
    "facebook/opt-66b",
    "facebook/wav2vec2-base",
    "facebook/wav2vec2-large",
    "google-bert/bert-base-cased",
    "google-bert/bert-base-uncased",
    "google-bert/bert-large-cased",
    "google-bert/bert-large-uncased",
    "google-t5/t5-base",
    "google-t5/t5-large",
    "google-t5/t5-small",
    "google/gemma-2-27b",
    "google/gemma-2-27b-it",
    "google/gemma-2-2b",
    "google/gemma-2-2b-it",
    "google/gemma-2-9b",
    "google/gemma-2-9b-it",
    "google/gemma-2b",
    "google/gemma-2b-it",
    "google/gemma-3-12b-it",
    "google/gemma-3-12b-pt",
    "google/gemma-3-1b-it",
    "google/gemma-3-1b-pt",
    "google/gemma-3-270m",
    "google/gemma-3-270m-it",
    "google/gemma-3-27b-it",
    "google/gemma-3-27b-pt",
    "google/gemma-3-4b-it",
    "google/gemma-3-4b-pt",
    "google/gemma-7b",
    "google/gemma-7b-it",
    "google/medgemma-27b-it",
    "google/medgemma-27b-text-it",
    "google/medgemma-4b-it",
    "google/medgemma-4b-pt",
    "gpt2",
    "gpt2-large",
    "gpt2-medium",
    "gpt2-xl",
    "llama-13b-hf",
    "llama-30b-hf",
    "llama-65b-hf",
    "llama-7b-hf",
    "meta-llama/Llama-2-13b-chat-hf",
    "meta-llama/Llama-2-13b-hf",
    "meta-llama/Llama-2-70b-chat-hf",
    "meta-llama/Llama-2-7b-chat-hf",
    "meta-llama/Llama-2-7b-hf",
    "meta-llama/Llama-3.1-70B",
    "meta-llama/Llama-3.1-70B-Instruct",
    "meta-llama/Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.2-1B",
    "meta-llama/Llama-3.2-1B-Instruct",
    "meta-llama/Llama-3.2-3B",
    "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct",
    "meta-llama/Meta-Llama-3-70B",
    "meta-llama/Meta-Llama-3-70B-Instruct",
    "meta-llama/Meta-Llama-3-8B",
    "meta-llama/Meta-Llama-3-8B-Instruct",
    "microsoft/phi-1",
    "microsoft/phi-1_5",
    "microsoft/phi-2",
    "microsoft/Phi-3-mini-4k-instruct",
    "microsoft/phi-4",
    "mistralai/Mistral-7B-Instruct-v0.1",
    "mistralai/Mistral-7B-v0.1",
    "mistralai/Mistral-Nemo-Base-2407",
    "mistralai/Mistral-Small-24B-Base-2501",
    "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "mistralai/Mixtral-8x7B-v0.1",
    "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "NeelNanda/Attn_Only_1L512W_C4_Code",
    "NeelNanda/Attn_Only_2L512W_C4_Code",
    "NeelNanda/Attn_Only_3L512W_C4_Code",
    "NeelNanda/Attn_Only_4L512W_C4_Code",
    "NeelNanda/GELU_1L512W_C4_Code",
    "NeelNanda/GELU_2L512W_C4_Code",
    "NeelNanda/GELU_3L512W_C4_Code",
    "NeelNanda/GELU_4L512W_C4_Code",
    "NeelNanda/SoLU_10L1280W_C4_Code",
    "NeelNanda/SoLU_10L_v22_old",
    "NeelNanda/SoLU_12L1536W_C4_Code",
    "NeelNanda/SoLU_12L_v23_old",
    "NeelNanda/SoLU_1L512W_C4_Code",
    "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "NeelNanda/SoLU_1L_v9_old",
    "NeelNanda/SoLU_2L512W_C4_Code",
    "NeelNanda/SoLU_2L_v10_old",
    "NeelNanda/SoLU_3L512W_C4_Code",
    "NeelNanda/SoLU_4L512W_C4_Code",
    "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "NeelNanda/SoLU_4L_v11_old",
    "NeelNanda/SoLU_6L768W_C4_Code",
    "NeelNanda/SoLU_6L_v13_old",
    "NeelNanda/SoLU_8L1024W_C4_Code",
    "NeelNanda/SoLU_8L_v21_old",
    "openai/gpt-oss-20b",
    "Qwen/Qwen-14B",
    "Qwen/Qwen-14B-Chat",
    "Qwen/Qwen-1_8B",
    "Qwen/Qwen-1_8B-Chat",
    "Qwen/Qwen-7B",
    "Qwen/Qwen-7B-Chat",
    "Qwen/Qwen1.5-0.5B",
    "Qwen/Qwen1.5-0.5B-Chat",
    "Qwen/Qwen1.5-1.8B",
    "Qwen/Qwen1.5-1.8B-Chat",
    "Qwen/Qwen1.5-14B",
    "Qwen/Qwen1.5-14B-Chat",
    "Qwen/Qwen1.5-4B",
    "Qwen/Qwen1.5-4B-Chat",
    "Qwen/Qwen1.5-7B",
    "Qwen/Qwen1.5-7B-Chat",
    "Qwen/Qwen2-0.5B",
    "Qwen/Qwen2-0.5B-Instruct",
    "Qwen/Qwen2-1.5B",
    "Qwen/Qwen2-1.5B-Instruct",
    "Qwen/Qwen2-7B",
    "Qwen/Qwen2-7B-Instruct",
    "Qwen/Qwen2.5-0.5B",
    "Qwen/Qwen2.5-0.5B-Instruct",
    "Qwen/Qwen2.5-1.5B",
    "Qwen/Qwen2.5-1.5B-Instruct",
    "Qwen/Qwen2.5-14B",
    "Qwen/Qwen2.5-14B-Instruct",
    "Qwen/Qwen2.5-32B",
    "Qwen/Qwen2.5-32B-Instruct",
    "Qwen/Qwen2.5-3B",
    "Qwen/Qwen2.5-3B-Instruct",
    "Qwen/Qwen2.5-72B",
    "Qwen/Qwen2.5-72B-Instruct",
    "Qwen/Qwen2.5-7B",
    "Qwen/Qwen2.5-7B-Instruct",
    "Qwen/Qwen3-0.6B",
    "Qwen/Qwen3-0.6B-Base",
    "Qwen/Qwen3-1.7B",
    "Qwen/Qwen3-14B",
    "Qwen/Qwen3-4B",
    "Qwen/Qwen3-8B",
    "Qwen/QwQ-32B-Preview",
    "roneneldan/TinyStories-1Layer-21M",
    "roneneldan/TinyStories-1M",
    "roneneldan/TinyStories-28M",
    "roneneldan/TinyStories-2Layers-33M",
    "roneneldan/TinyStories-33M",
    "roneneldan/TinyStories-3M",
    "roneneldan/TinyStories-8M",
    "roneneldan/TinyStories-Instruct-1M",
    "roneneldan/TinyStories-Instruct-28M",
    "roneneldan/TinyStories-Instruct-2Layers-33M",
    "roneneldan/TinyStories-Instruct-33M",
    "roneneldan/TinyStories-Instruct-3M",
    "roneneldan/TinyStories-Instruct-8M",
    "roneneldan/TinyStories-Instuct-1Layer-21M",
    "stabilityai/stablelm-base-alpha-3b",
    "stabilityai/stablelm-base-alpha-7b",
    "stabilityai/stablelm-tuned-alpha-3b",
    "stabilityai/stablelm-tuned-alpha-7b",
    "stanford-crfm/alias-gpt2-small-x21",
    "stanford-crfm/arwen-gpt2-medium-x21",
    "stanford-crfm/battlestar-gpt2-small-x49",
    "stanford-crfm/beren-gpt2-medium-x49",
    "stanford-crfm/caprica-gpt2-small-x81",
    "stanford-crfm/celebrimbor-gpt2-medium-x81",
    "stanford-crfm/darkmatter-gpt2-small-x343",
    "stanford-crfm/durin-gpt2-medium-x343",
    "stanford-crfm/eowyn-gpt2-medium-x777",
    "stanford-crfm/expanse-gpt2-small-x777",
    "swiss-ai/Apertus-8B-2509",
    "swiss-ai/Apertus-8B-Instruct-2509",
)

TRANSFORMER_LENS_COMMON_ALIASES: tuple[str, ...] = (
    "gpt2-small",
    "gpt2-xs",
    "gpt-j",
    "gptj",
    "gpt-neo",
    "gpt-neox",
    "neox",
    "pythia",
    "opt",
    "bloom-560m",
    "llama-7b",
    "llama-13b",
    "llama-30b",
    "llama-65b",
    "mistral-7b",
    "mixtral",
    "mamba-130m",
    "mamba-codestral",
    "qwen3-8b",
    "qwen3-14b",
    "gemma-2b",
    "gemma-7b",
    "phi-2",
    "tiny-stories-1m",
    "solu-1l",
    "solu-2l",
    "gelu-2l",
    "attn-only-2l",
    "attn-only-3l",
    "redwood_attn_2l",
    "othello-gpt",
    "bert-base-uncased",
    "roberta-base",
    "distilbert-base-uncased",
    "t5-small",
    "hubert-base-ls960",
    "wav2vec2-base",
)

TRANSFORMER_LENS_NATIVE_CHECKPOINT_ALIASES: dict[str, str] = {
    "redwood_attn_2l": "ArthurConmy/redwood_attn_2l",
    "othello-gpt": "Baidicoot/Othello-GPT-Transformer-Lens",
    "attn-only-2l-demo": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "attn-only-2l-shortformer-6b-big-lr": (
        "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr"
    ),
    "attn-only-2l-induction-demo": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "attn-only-demo": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "attn-only-1l": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "attn-only-1l-new": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "attn-only-1l-c4-code": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "attn-only-2l": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "attn-only-2l-new": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "attn-only-2l-c4-code": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "attn-only-3l": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "attn-only-3l-new": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "attn-only-3l-c4-code": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "attn-only-4l": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "attn-only-4l-new": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "attn-only-4l-c4-code": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "gelu-1l": "NeelNanda/GELU_1L512W_C4_Code",
    "gelu-1l-new": "NeelNanda/GELU_1L512W_C4_Code",
    "gelu-1l-c4-code": "NeelNanda/GELU_1L512W_C4_Code",
    "gelu-2l": "NeelNanda/GELU_2L512W_C4_Code",
    "gelu-2l-new": "NeelNanda/GELU_2L512W_C4_Code",
    "gelu-2l-c4-code": "NeelNanda/GELU_2L512W_C4_Code",
    "gelu-3l": "NeelNanda/GELU_3L512W_C4_Code",
    "gelu-3l-new": "NeelNanda/GELU_3L512W_C4_Code",
    "gelu-3l-c4-code": "NeelNanda/GELU_3L512W_C4_Code",
    "gelu-4l": "NeelNanda/GELU_4L512W_C4_Code",
    "gelu-4l-new": "NeelNanda/GELU_4L512W_C4_Code",
    "gelu-4l-c4-code": "NeelNanda/GELU_4L512W_C4_Code",
    "solu-1l": "NeelNanda/SoLU_1L512W_C4_Code",
    "solu-1l-new": "NeelNanda/SoLU_1L512W_C4_Code",
    "solu-1l-c4-code": "NeelNanda/SoLU_1L512W_C4_Code",
    "solu-1l-wiki": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "solu-1l-wiki-finetune": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "solu-1l-finetune": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "solu-1l-pile": "NeelNanda/SoLU_1L_v9_old",
    "solu-1l-old": "NeelNanda/SoLU_1L_v9_old",
    "solu-2l": "NeelNanda/SoLU_2L512W_C4_Code",
    "solu-2l-new": "NeelNanda/SoLU_2L512W_C4_Code",
    "solu-2l-c4-code": "NeelNanda/SoLU_2L512W_C4_Code",
    "solu-2l-pile": "NeelNanda/SoLU_2L_v10_old",
    "solu-2l-old": "NeelNanda/SoLU_2L_v10_old",
    "solu-3l": "NeelNanda/SoLU_3L512W_C4_Code",
    "solu-3l-new": "NeelNanda/SoLU_3L512W_C4_Code",
    "solu-3l-c4-code": "NeelNanda/SoLU_3L512W_C4_Code",
    "solu-4l": "NeelNanda/SoLU_4L512W_C4_Code",
    "solu-4l-new": "NeelNanda/SoLU_4L512W_C4_Code",
    "solu-4l-c4-code": "NeelNanda/SoLU_4L512W_C4_Code",
    "solu-4l-wiki": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "solu-4l-wiki-finetune": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "solu-4l-finetune": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "solu-4l-pile": "NeelNanda/SoLU_4L_v11_old",
    "solu-4l-old": "NeelNanda/SoLU_4L_v11_old",
    "solu-6l": "NeelNanda/SoLU_6L768W_C4_Code",
    "solu-6l-new": "NeelNanda/SoLU_6L768W_C4_Code",
    "solu-6l-c4-code": "NeelNanda/SoLU_6L768W_C4_Code",
    "solu-6l-pile": "NeelNanda/SoLU_6L_v13_old",
    "solu-6l-old": "NeelNanda/SoLU_6L_v13_old",
    "solu-8l": "NeelNanda/SoLU_8L1024W_C4_Code",
    "solu-8l-new": "NeelNanda/SoLU_8L1024W_C4_Code",
    "solu-8l-c4-code": "NeelNanda/SoLU_8L1024W_C4_Code",
    "solu-8l-pile": "NeelNanda/SoLU_8L_v21_old",
    "solu-8l-old": "NeelNanda/SoLU_8L_v21_old",
    "solu-10l": "NeelNanda/SoLU_10L1280W_C4_Code",
    "solu-10l-new": "NeelNanda/SoLU_10L1280W_C4_Code",
    "solu-10l-c4-code": "NeelNanda/SoLU_10L1280W_C4_Code",
    "solu-10l-pile": "NeelNanda/SoLU_10L_v22_old",
    "solu-10l-old": "NeelNanda/SoLU_10L_v22_old",
    "solu-12l": "NeelNanda/SoLU_12L1536W_C4_Code",
    "solu-12l-new": "NeelNanda/SoLU_12L1536W_C4_Code",
    "solu-12l-c4-code": "NeelNanda/SoLU_12L1536W_C4_Code",
    "solu-12l-pile": "NeelNanda/SoLU_12L_v23_old",
    "solu-12l-old": "NeelNanda/SoLU_12L_v23_old",
}

TRANSFORMER_LENS_OFFICIAL_MODEL_ALIASES: dict[str, str] = {
    "01-ai/yi-34b": "01-ai/Yi-34B",
    "01-ai/yi-34b-chat": "01-ai/Yi-34B-Chat",
    "01-ai/yi-6b": "01-ai/Yi-6B",
    "01-ai/yi-6b-chat": "01-ai/Yi-6B-Chat",
    "ai-forever/mgpt": "ai-forever/mGPT",
    "alias-gpt2-small-x21": "stanford-crfm/alias-gpt2-small-x21",
    "allenai/olmo-1b-hf": "allenai/OLMo-1B-hf",
    "allenai/olmo-2-0425-1b": "allenai/OLMo-2-0425-1B",
    "allenai/olmo-2-1124-7b": "allenai/OLMo-2-1124-7B",
    "allenai/olmo-3-32b-think": "allenai/Olmo-3-32B-Think",
    "allenai/olmo-3-7b-instruct": "allenai/Olmo-3-7B-Instruct",
    "allenai/olmo-3-7b-think": "allenai/Olmo-3-7B-Think",
    "allenai/olmo-3.1-32b-instruct": "allenai/Olmo-3.1-32B-Instruct",
    "allenai/olmo-3.1-32b-think": "allenai/Olmo-3.1-32B-Think",
    "allenai/olmo-7b-hf": "allenai/OLMo-7B-hf",
    "allenai/olmoe-1b-7b-0924": "allenai/OLMoE-1B-7B-0924",
    "apertus": "swiss-ai/Apertus-8B-2509",
    "apertus-8b": "swiss-ai/Apertus-8B-2509",
    "apertus-8b-instruct": "swiss-ai/Apertus-8B-Instruct-2509",
    "apertus-instruct": "swiss-ai/Apertus-8B-Instruct-2509",
    "arthurconmy/redwood_attn_2l": "ArthurConmy/redwood_attn_2l",
    "arwen-gpt2-medium-x21": "stanford-crfm/arwen-gpt2-medium-x21",
    "attn-only-1l": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "attn-only-1l-c4-code": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "attn-only-1l-new": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "attn-only-2l": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "attn-only-2l-c4-code": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "attn-only-2l-demo": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "attn-only-2l-induction-demo": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "attn-only-2l-new": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "attn-only-2l-shortformer-6b-big-lr": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "attn-only-3l": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "attn-only-3l-c4-code": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "attn-only-3l-new": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "attn-only-4l": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "attn-only-4l-c4-code": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "attn-only-4l-new": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "attn-only-demo": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "baidicoot/othello-gpt-transformer-lens": "Baidicoot/Othello-GPT-Transformer-Lens",
    "battlestar-gpt2-small-x49": "stanford-crfm/battlestar-gpt2-small-x49",
    "beren-gpt2-medium-x49": "stanford-crfm/beren-gpt2-medium-x49",
    "bert-base-cased": "google-bert/bert-base-cased",
    "bert-base-uncased": "google-bert/bert-base-uncased",
    "bert-large-cased": "google-bert/bert-large-cased",
    "bert-large-uncased": "google-bert/bert-large-uncased",
    "bigcode/santacoder": "bigcode/santacoder",
    "bigscience/bloom-1b1": "bigscience/bloom-1b1",
    "bigscience/bloom-1b7": "bigscience/bloom-1b7",
    "bigscience/bloom-3b": "bigscience/bloom-3b",
    "bigscience/bloom-560m": "bigscience/bloom-560m",
    "bigscience/bloom-7b1": "bigscience/bloom-7b1",
    "bloom-1b1": "bigscience/bloom-1b1",
    "bloom-1b7": "bigscience/bloom-1b7",
    "bloom-3b": "bigscience/bloom-3b",
    "bloom-560m": "bigscience/bloom-560m",
    "bloom-7b1": "bigscience/bloom-7b1",
    "caprica-gpt2-small-x81": "stanford-crfm/caprica-gpt2-small-x81",
    "celebrimbor-gpt2-medium-x81": "stanford-crfm/celebrimbor-gpt2-medium-x81",
    "codellama-7b-instruct": "codellama/CodeLlama-7b-Instruct-hf",
    "codellama-7b-python": "codellama/CodeLlama-7b-Python-hf",
    "codellama/codellama-7b-hf": "codellama/CodeLlama-7b-hf",
    "codellama/codellama-7b-instruct-hf": "codellama/CodeLlama-7b-Instruct-hf",
    "codellama/codellama-7b-python-hf": "codellama/CodeLlama-7b-Python-hf",
    "codellamallama-2-7b": "codellama/CodeLlama-7b-hf",
    "darkmatter-gpt2-small-x343": "stanford-crfm/darkmatter-gpt2-small-x343",
    "distil-gpt2": "distilgpt2",
    "distilgpt2": "distilgpt2",
    "distill-gpt2": "distilgpt2",
    "distillgpt2": "distilgpt2",
    "durin-gpt2-medium-x343": "stanford-crfm/durin-gpt2-medium-x343",
    "eleutherai/gpt-j-6b": "EleutherAI/gpt-j-6B",
    "eleutherai/gpt-neo-1.3b": "EleutherAI/gpt-neo-1.3B",
    "eleutherai/gpt-neo-125m": "EleutherAI/gpt-neo-125M",
    "eleutherai/gpt-neo-2.7b": "EleutherAI/gpt-neo-2.7B",
    "eleutherai/gpt-neox-20b": "EleutherAI/gpt-neox-20b",
    "eleutherai/pythia-1.3b": "EleutherAI/pythia-1.4b",
    "eleutherai/pythia-1.3b-deduped": "EleutherAI/pythia-1.4b-deduped",
    "eleutherai/pythia-1.3b-deduped-v0": "EleutherAI/pythia-1.4b-deduped-v0",
    "eleutherai/pythia-1.3b-v0": "EleutherAI/pythia-1.4b-v0",
    "eleutherai/pythia-1.4b": "EleutherAI/pythia-1.4b",
    "eleutherai/pythia-1.4b-deduped": "EleutherAI/pythia-1.4b-deduped",
    "eleutherai/pythia-1.4b-deduped-v0": "EleutherAI/pythia-1.4b-deduped-v0",
    "eleutherai/pythia-1.4b-v0": "EleutherAI/pythia-1.4b-v0",
    "eleutherai/pythia-125m": "EleutherAI/pythia-160m",
    "eleutherai/pythia-125m-deduped": "EleutherAI/pythia-160m-deduped",
    "eleutherai/pythia-125m-deduped-v0": "EleutherAI/pythia-160m-deduped-v0",
    "eleutherai/pythia-125m-seed1": "EleutherAI/pythia-160m-seed1",
    "eleutherai/pythia-125m-seed2": "EleutherAI/pythia-160m-seed2",
    "eleutherai/pythia-125m-seed3": "EleutherAI/pythia-160m-seed3",
    "eleutherai/pythia-125m-v0": "EleutherAI/pythia-160m-v0",
    "eleutherai/pythia-12b": "EleutherAI/pythia-12b",
    "eleutherai/pythia-12b-deduped": "EleutherAI/pythia-12b-deduped",
    "eleutherai/pythia-12b-deduped-v0": "EleutherAI/pythia-12b-deduped-v0",
    "eleutherai/pythia-12b-v0": "EleutherAI/pythia-12b-v0",
    "eleutherai/pythia-13b": "EleutherAI/pythia-12b",
    "eleutherai/pythia-13b-deduped": "EleutherAI/pythia-12b-deduped",
    "eleutherai/pythia-13b-deduped-v0": "EleutherAI/pythia-12b-deduped-v0",
    "eleutherai/pythia-13b-v0": "EleutherAI/pythia-12b-v0",
    "eleutherai/pythia-14m": "EleutherAI/pythia-14m",
    "eleutherai/pythia-160m": "EleutherAI/pythia-160m",
    "eleutherai/pythia-160m-deduped": "EleutherAI/pythia-160m-deduped",
    "eleutherai/pythia-160m-deduped-v0": "EleutherAI/pythia-160m-deduped-v0",
    "eleutherai/pythia-160m-seed1": "EleutherAI/pythia-160m-seed1",
    "eleutherai/pythia-160m-seed2": "EleutherAI/pythia-160m-seed2",
    "eleutherai/pythia-160m-seed3": "EleutherAI/pythia-160m-seed3",
    "eleutherai/pythia-160m-v0": "EleutherAI/pythia-160m-v0",
    "eleutherai/pythia-19m": "EleutherAI/pythia-70m",
    "eleutherai/pythia-19m-deduped": "EleutherAI/pythia-70m-deduped",
    "eleutherai/pythia-19m-deduped-v0": "EleutherAI/pythia-70m-deduped-v0",
    "eleutherai/pythia-19m-v0": "EleutherAI/pythia-70m-v0",
    "eleutherai/pythia-1b": "EleutherAI/pythia-1b",
    "eleutherai/pythia-1b-deduped": "EleutherAI/pythia-1b-deduped",
    "eleutherai/pythia-1b-deduped-v0": "EleutherAI/pythia-1b-deduped-v0",
    "eleutherai/pythia-1b-v0": "EleutherAI/pythia-1b-v0",
    "eleutherai/pythia-2.7b": "EleutherAI/pythia-2.8b",
    "eleutherai/pythia-2.7b-deduped": "EleutherAI/pythia-2.8b-deduped",
    "eleutherai/pythia-2.7b-deduped-v0": "EleutherAI/pythia-2.8b-deduped-v0",
    "eleutherai/pythia-2.7b-v0": "EleutherAI/pythia-2.8b-v0",
    "eleutherai/pythia-2.8b": "EleutherAI/pythia-2.8b",
    "eleutherai/pythia-2.8b-deduped": "EleutherAI/pythia-2.8b-deduped",
    "eleutherai/pythia-2.8b-deduped-v0": "EleutherAI/pythia-2.8b-deduped-v0",
    "eleutherai/pythia-2.8b-v0": "EleutherAI/pythia-2.8b-v0",
    "eleutherai/pythia-31m": "EleutherAI/pythia-31m",
    "eleutherai/pythia-350m": "EleutherAI/pythia-410m",
    "eleutherai/pythia-350m-deduped": "EleutherAI/pythia-410m-deduped",
    "eleutherai/pythia-350m-deduped-v0": "EleutherAI/pythia-410m-deduped-v0",
    "eleutherai/pythia-350m-v0": "EleutherAI/pythia-410m-v0",
    "eleutherai/pythia-410m": "EleutherAI/pythia-410m",
    "eleutherai/pythia-410m-deduped": "EleutherAI/pythia-410m-deduped",
    "eleutherai/pythia-410m-deduped-v0": "EleutherAI/pythia-410m-deduped-v0",
    "eleutherai/pythia-410m-v0": "EleutherAI/pythia-410m-v0",
    "eleutherai/pythia-6.7b": "EleutherAI/pythia-6.9b",
    "eleutherai/pythia-6.7b-deduped": "EleutherAI/pythia-6.9b-deduped",
    "eleutherai/pythia-6.7b-deduped-v0": "EleutherAI/pythia-6.9b-deduped-v0",
    "eleutherai/pythia-6.7b-v0": "EleutherAI/pythia-6.9b-v0",
    "eleutherai/pythia-6.9b": "EleutherAI/pythia-6.9b",
    "eleutherai/pythia-6.9b-deduped": "EleutherAI/pythia-6.9b-deduped",
    "eleutherai/pythia-6.9b-deduped-v0": "EleutherAI/pythia-6.9b-deduped-v0",
    "eleutherai/pythia-6.9b-v0": "EleutherAI/pythia-6.9b-v0",
    "eleutherai/pythia-70m": "EleutherAI/pythia-70m",
    "eleutherai/pythia-70m-deduped": "EleutherAI/pythia-70m-deduped",
    "eleutherai/pythia-70m-deduped-v0": "EleutherAI/pythia-70m-deduped-v0",
    "eleutherai/pythia-70m-v0": "EleutherAI/pythia-70m-v0",
    "eleutherai/pythia-800m": "EleutherAI/pythia-1b",
    "eleutherai/pythia-800m-deduped": "EleutherAI/pythia-1b-deduped",
    "eleutherai/pythia-800m-deduped-v0": "EleutherAI/pythia-1b-deduped-v0",
    "eleutherai/pythia-800m-v0": "EleutherAI/pythia-1b-v0",
    "eowyn-gpt2-medium-x777": "stanford-crfm/eowyn-gpt2-medium-x777",
    "expanse-gpt2-small-x777": "stanford-crfm/expanse-gpt2-small-x777",
    "facebook/hubert-base-ls960": "facebook/hubert-base-ls960",
    "facebook/opt-1.3b": "facebook/opt-1.3b",
    "facebook/opt-125m": "facebook/opt-125m",
    "facebook/opt-13b": "facebook/opt-13b",
    "facebook/opt-2.7b": "facebook/opt-2.7b",
    "facebook/opt-30b": "facebook/opt-30b",
    "facebook/opt-6.7b": "facebook/opt-6.7b",
    "facebook/opt-66b": "facebook/opt-66b",
    "facebook/wav2vec2-base": "facebook/wav2vec2-base",
    "facebook/wav2vec2-large": "facebook/wav2vec2-large",
    "gelu-1l": "NeelNanda/GELU_1L512W_C4_Code",
    "gelu-1l-c4-code": "NeelNanda/GELU_1L512W_C4_Code",
    "gelu-1l-new": "NeelNanda/GELU_1L512W_C4_Code",
    "gelu-2l": "NeelNanda/GELU_2L512W_C4_Code",
    "gelu-2l-c4-code": "NeelNanda/GELU_2L512W_C4_Code",
    "gelu-2l-new": "NeelNanda/GELU_2L512W_C4_Code",
    "gelu-3l": "NeelNanda/GELU_3L512W_C4_Code",
    "gelu-3l-c4-code": "NeelNanda/GELU_3L512W_C4_Code",
    "gelu-3l-new": "NeelNanda/GELU_3L512W_C4_Code",
    "gelu-4l": "NeelNanda/GELU_4L512W_C4_Code",
    "gelu-4l-c4-code": "NeelNanda/GELU_4L512W_C4_Code",
    "gelu-4l-new": "NeelNanda/GELU_4L512W_C4_Code",
    "gemma-2-27b": "google/gemma-2-27b",
    "gemma-2-27b-it": "google/gemma-2-27b-it",
    "gemma-2-2b": "google/gemma-2-2b",
    "gemma-2-2b-it": "google/gemma-2-2b-it",
    "gemma-2-9b": "google/gemma-2-9b",
    "gemma-2-9b-it": "google/gemma-2-9b-it",
    "gemma-2b": "google/gemma-2b",
    "gemma-2b-it": "google/gemma-2b-it",
    "gemma-3-12b-it": "google/gemma-3-12b-it",
    "gemma-3-12b-pt": "google/gemma-3-12b-pt",
    "gemma-3-1b-it": "google/gemma-3-1b-it",
    "gemma-3-1b-pt": "google/gemma-3-1b-pt",
    "gemma-3-270m": "google/gemma-3-270m",
    "gemma-3-270m-it": "google/gemma-3-270m-it",
    "gemma-3-27b-it": "google/gemma-3-27b-it",
    "gemma-3-27b-pt": "google/gemma-3-27b-pt",
    "gemma-3-4b-it": "google/gemma-3-4b-it",
    "gemma-3-4b-pt": "google/gemma-3-4b-pt",
    "gemma-7b": "google/gemma-7b",
    "gemma-7b-it": "google/gemma-7b-it",
    "google-bert/bert-base-cased": "google-bert/bert-base-cased",
    "google-bert/bert-base-uncased": "google-bert/bert-base-uncased",
    "google-bert/bert-large-cased": "google-bert/bert-large-cased",
    "google-bert/bert-large-uncased": "google-bert/bert-large-uncased",
    "google-t5/t5-base": "google-t5/t5-base",
    "google-t5/t5-large": "google-t5/t5-large",
    "google-t5/t5-small": "google-t5/t5-small",
    "google/gemma-2-27b": "google/gemma-2-27b",
    "google/gemma-2-27b-it": "google/gemma-2-27b-it",
    "google/gemma-2-2b": "google/gemma-2-2b",
    "google/gemma-2-2b-it": "google/gemma-2-2b-it",
    "google/gemma-2-9b": "google/gemma-2-9b",
    "google/gemma-2-9b-it": "google/gemma-2-9b-it",
    "google/gemma-2b": "google/gemma-2b",
    "google/gemma-2b-it": "google/gemma-2b-it",
    "google/gemma-3-12b-it": "google/gemma-3-12b-it",
    "google/gemma-3-12b-pt": "google/gemma-3-12b-pt",
    "google/gemma-3-1b-it": "google/gemma-3-1b-it",
    "google/gemma-3-1b-pt": "google/gemma-3-1b-pt",
    "google/gemma-3-270m": "google/gemma-3-270m",
    "google/gemma-3-270m-it": "google/gemma-3-270m-it",
    "google/gemma-3-27b-it": "google/gemma-3-27b-it",
    "google/gemma-3-27b-pt": "google/gemma-3-27b-pt",
    "google/gemma-3-4b-it": "google/gemma-3-4b-it",
    "google/gemma-3-4b-pt": "google/gemma-3-4b-pt",
    "google/gemma-7b": "google/gemma-7b",
    "google/gemma-7b-it": "google/gemma-7b-it",
    "google/medgemma-27b-it": "google/medgemma-27b-it",
    "google/medgemma-27b-text-it": "google/medgemma-27b-text-it",
    "google/medgemma-4b-it": "google/medgemma-4b-it",
    "google/medgemma-4b-pt": "google/medgemma-4b-pt",
    "gpt-j": "EleutherAI/gpt-j-6B",
    "gpt-j-6b": "EleutherAI/gpt-j-6B",
    "gpt-neo-1.3b": "EleutherAI/gpt-neo-1.3B",
    "gpt-neo-125m": "EleutherAI/gpt-neo-125M",
    "gpt-neo-2.7b": "EleutherAI/gpt-neo-2.7B",
    "gpt-neo-large": "EleutherAI/gpt-neo-2.7B",
    "gpt-neo-medium": "EleutherAI/gpt-neo-1.3B",
    "gpt-neo-small": "EleutherAI/gpt-neo-125M",
    "gpt-neox": "EleutherAI/gpt-neox-20b",
    "gpt-neox-20b": "EleutherAI/gpt-neox-20b",
    "gpt-oss": "openai/gpt-oss-20b",
    "gpt-oss-20b": "openai/gpt-oss-20b",
    "gpt2": "gpt2",
    "gpt2-large": "gpt2-large",
    "gpt2-medium": "gpt2-medium",
    "gpt2-medium-small-a": "stanford-crfm/arwen-gpt2-medium-x21",
    "gpt2-medium-small-b": "stanford-crfm/beren-gpt2-medium-x49",
    "gpt2-medium-small-c": "stanford-crfm/celebrimbor-gpt2-medium-x81",
    "gpt2-medium-small-d": "stanford-crfm/durin-gpt2-medium-x343",
    "gpt2-medium-small-e": "stanford-crfm/eowyn-gpt2-medium-x777",
    "gpt2-mistral-small-a": "stanford-crfm/alias-gpt2-small-x21",
    "gpt2-mistral-small-b": "stanford-crfm/battlestar-gpt2-small-x49",
    "gpt2-mistral-small-c": "stanford-crfm/caprica-gpt2-small-x81",
    "gpt2-mistral-small-d": "stanford-crfm/darkmatter-gpt2-small-x343",
    "gpt2-mistral-small-e": "stanford-crfm/expanse-gpt2-small-x777",
    "gpt2-small": "gpt2",
    "gpt2-stanford-medium-a": "stanford-crfm/arwen-gpt2-medium-x21",
    "gpt2-stanford-medium-b": "stanford-crfm/beren-gpt2-medium-x49",
    "gpt2-stanford-medium-d": "stanford-crfm/durin-gpt2-medium-x343",
    "gpt2-stanford-medium-e": "stanford-crfm/eowyn-gpt2-medium-x777",
    "gpt2-stanford-small-a": "stanford-crfm/alias-gpt2-small-x21",
    "gpt2-stanford-small-c": "stanford-crfm/caprica-gpt2-small-x81",
    "gpt2-xl": "gpt2-xl",
    "gpt2-xs": "distilgpt2",
    "gptj": "EleutherAI/gpt-j-6B",
    "hubert-base-ls960": "facebook/hubert-base-ls960",
    "llama-13b": "llama-13b-hf",
    "llama-13b-hf": "llama-13b-hf",
    "llama-2-13b": "meta-llama/Llama-2-13b-hf",
    "llama-2-13b-chat": "meta-llama/Llama-2-13b-chat-hf",
    "llama-2-70b-chat": "meta-llama/Llama-2-70b-chat-hf",
    "llama-2-7b": "meta-llama/Llama-2-7b-hf",
    "llama-2-7b-chat": "meta-llama/Llama-2-7b-chat-hf",
    "llama-30b": "llama-30b-hf",
    "llama-30b-hf": "llama-30b-hf",
    "llama-65b": "llama-65b-hf",
    "llama-65b-hf": "llama-65b-hf",
    "llama-7b": "llama-7b-hf",
    "llama-7b-hf": "llama-7b-hf",
    "medgemma-27b-it": "google/medgemma-27b-it",
    "medgemma-27b-text-it": "google/medgemma-27b-text-it",
    "medgemma-4b-it": "google/medgemma-4b-it",
    "medgemma-4b-pt": "google/medgemma-4b-pt",
    "meta-llama-2-70b-chat-hf": "meta-llama/Llama-2-70b-chat-hf",
    "meta-llama/llama-2-13b-chat-hf": "meta-llama/Llama-2-13b-chat-hf",
    "meta-llama/llama-2-13b-hf": "meta-llama/Llama-2-13b-hf",
    "meta-llama/llama-2-70b-chat-hf": "meta-llama/Llama-2-70b-chat-hf",
    "meta-llama/llama-2-7b-chat-hf": "meta-llama/Llama-2-7b-chat-hf",
    "meta-llama/llama-2-7b-hf": "meta-llama/Llama-2-7b-hf",
    "meta-llama/llama-3.1-70b": "meta-llama/Llama-3.1-70B",
    "meta-llama/llama-3.1-70b-instruct": "meta-llama/Llama-3.1-70B-Instruct",
    "meta-llama/llama-3.1-8b": "meta-llama/Llama-3.1-8B",
    "meta-llama/llama-3.1-8b-instruct": "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/llama-3.2-1b": "meta-llama/Llama-3.2-1B",
    "meta-llama/llama-3.2-1b-instruct": "meta-llama/Llama-3.2-1B-Instruct",
    "meta-llama/llama-3.2-3b": "meta-llama/Llama-3.2-3B",
    "meta-llama/llama-3.2-3b-instruct": "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/llama-3.3-70b-instruct": "meta-llama/Llama-3.3-70B-Instruct",
    "meta-llama/meta-llama-3-70b": "meta-llama/Meta-Llama-3-70B",
    "meta-llama/meta-llama-3-70b-instruct": "meta-llama/Meta-Llama-3-70B-Instruct",
    "meta-llama/meta-llama-3-8b": "meta-llama/Meta-Llama-3-8B",
    "meta-llama/meta-llama-3-8b-instruct": "meta-llama/Meta-Llama-3-8B-Instruct",
    "mgpt": "ai-forever/mGPT",
    "microsoft/phi-1": "microsoft/phi-1",
    "microsoft/phi-1_5": "microsoft/phi-1_5",
    "microsoft/phi-2": "microsoft/phi-2",
    "microsoft/phi-3-mini-4k-instruct": "microsoft/Phi-3-mini-4k-instruct",
    "microsoft/phi-4": "microsoft/phi-4",
    "mistral-7b": "mistralai/Mistral-7B-v0.1",
    "mistral-7b-instruct": "mistralai/Mistral-7B-Instruct-v0.1",
    "mistral-nemo-base-2407": "mistralai/Mistral-Nemo-Base-2407",
    "mistralai/mistral-7b-instruct-v0.1": "mistralai/Mistral-7B-Instruct-v0.1",
    "mistralai/mistral-7b-v0.1": "mistralai/Mistral-7B-v0.1",
    "mistralai/mistral-nemo-base-2407": "mistralai/Mistral-Nemo-Base-2407",
    "mistralai/mistral-small-24b-base-2501": "mistralai/Mistral-Small-24B-Base-2501",
    "mistralai/mixtral-8x7b-instruct-v0.1": "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "mistralai/mixtral-8x7b-v0.1": "mistralai/Mixtral-8x7B-v0.1",
    "mixtral": "mistralai/Mixtral-8x7B-v0.1",
    "mixtral-8x7b": "mistralai/Mixtral-8x7B-v0.1",
    "mixtral-8x7b-instruct": "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "mixtral-instruct": "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "neelnanda/attn-only-2l512w-shortformer-6b-big-lr": "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "neelnanda/attn_only_1l512w_c4_code": "NeelNanda/Attn_Only_1L512W_C4_Code",
    "neelnanda/attn_only_2l512w_c4_code": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "neelnanda/attn_only_3l512w_c4_code": "NeelNanda/Attn_Only_3L512W_C4_Code",
    "neelnanda/attn_only_4l512w_c4_code": "NeelNanda/Attn_Only_4L512W_C4_Code",
    "neelnanda/gelu_1l512w_c4_code": "NeelNanda/GELU_1L512W_C4_Code",
    "neelnanda/gelu_2l512w_c4_code": "NeelNanda/GELU_2L512W_C4_Code",
    "neelnanda/gelu_3l512w_c4_code": "NeelNanda/GELU_3L512W_C4_Code",
    "neelnanda/gelu_4l512w_c4_code": "NeelNanda/GELU_4L512W_C4_Code",
    "neelnanda/solu_10l1280w_c4_code": "NeelNanda/SoLU_10L1280W_C4_Code",
    "neelnanda/solu_10l_v22_old": "NeelNanda/SoLU_10L_v22_old",
    "neelnanda/solu_12l1536w_c4_code": "NeelNanda/SoLU_12L1536W_C4_Code",
    "neelnanda/solu_12l_v23_old": "NeelNanda/SoLU_12L_v23_old",
    "neelnanda/solu_1l512w_c4_code": "NeelNanda/SoLU_1L512W_C4_Code",
    "neelnanda/solu_1l512w_wiki_finetune": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "neelnanda/solu_1l_v9_old": "NeelNanda/SoLU_1L_v9_old",
    "neelnanda/solu_2l512w_c4_code": "NeelNanda/SoLU_2L512W_C4_Code",
    "neelnanda/solu_2l_v10_old": "NeelNanda/SoLU_2L_v10_old",
    "neelnanda/solu_3l512w_c4_code": "NeelNanda/SoLU_3L512W_C4_Code",
    "neelnanda/solu_4l512w_c4_code": "NeelNanda/SoLU_4L512W_C4_Code",
    "neelnanda/solu_4l512w_wiki_finetune": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "neelnanda/solu_4l_v11_old": "NeelNanda/SoLU_4L_v11_old",
    "neelnanda/solu_6l768w_c4_code": "NeelNanda/SoLU_6L768W_C4_Code",
    "neelnanda/solu_6l_v13_old": "NeelNanda/SoLU_6L_v13_old",
    "neelnanda/solu_8l1024w_c4_code": "NeelNanda/SoLU_8L1024W_C4_Code",
    "neelnanda/solu_8l_v21_old": "NeelNanda/SoLU_8L_v21_old",
    "neo": "EleutherAI/gpt-neo-125M",
    "neo-large": "EleutherAI/gpt-neo-2.7B",
    "neo-medium": "EleutherAI/gpt-neo-1.3B",
    "neo-small": "EleutherAI/gpt-neo-125M",
    "neox": "EleutherAI/gpt-neox-20b",
    "olmo-1b": "allenai/OLMo-1B-hf",
    "olmo-2-1b": "allenai/OLMo-2-0425-1B",
    "olmo-2-7b": "allenai/OLMo-2-1124-7B",
    "olmo-3-32b-think": "allenai/Olmo-3-32B-Think",
    "olmo-3-7b-instruct": "allenai/Olmo-3-7B-Instruct",
    "olmo-3-7b-think": "allenai/Olmo-3-7B-Think",
    "olmo-3.1-32b-instruct": "allenai/Olmo-3.1-32B-Instruct",
    "olmo-3.1-32b-think": "allenai/Olmo-3.1-32B-Think",
    "olmo-7b": "allenai/OLMo-7B-hf",
    "olmoe": "allenai/OLMoE-1B-7B-0924",
    "openai/gpt-oss-20b": "openai/gpt-oss-20b",
    "opt": "facebook/opt-125m",
    "opt-1.3b": "facebook/opt-1.3b",
    "opt-125m": "facebook/opt-125m",
    "opt-13b": "facebook/opt-13b",
    "opt-2.7b": "facebook/opt-2.7b",
    "opt-30b": "facebook/opt-30b",
    "opt-6.7b": "facebook/opt-6.7b",
    "opt-66b": "facebook/opt-66b",
    "opt-large": "facebook/opt-2.7b",
    "opt-medium": "facebook/opt-1.3b",
    "opt-small": "facebook/opt-125m",
    "opt-xl": "facebook/opt-6.7b",
    "opt-xxl": "facebook/opt-13b",
    "opt-xxxl": "facebook/opt-30b",
    "opt-xxxxl": "facebook/opt-66b",
    "othello-gpt": "Baidicoot/Othello-GPT-Transformer-Lens",
    "phi-1": "microsoft/phi-1",
    "phi-1_5": "microsoft/phi-1_5",
    "phi-2": "microsoft/phi-2",
    "phi-3": "microsoft/Phi-3-mini-4k-instruct",
    "phi-4": "microsoft/phi-4",
    "pythia": "EleutherAI/pythia-70m",
    "pythia-1.3b": "EleutherAI/pythia-1.4b",
    "pythia-1.3b-deduped": "EleutherAI/pythia-1.4b-deduped",
    "pythia-1.3b-deduped-v0": "EleutherAI/pythia-1.4b-deduped-v0",
    "pythia-1.3b-v0": "EleutherAI/pythia-1.4b-v0",
    "pythia-1.4b": "EleutherAI/pythia-1.4b",
    "pythia-1.4b-deduped": "EleutherAI/pythia-1.4b-deduped",
    "pythia-1.4b-deduped-v0": "EleutherAI/pythia-1.4b-deduped-v0",
    "pythia-1.4b-v0": "EleutherAI/pythia-1.4b-v0",
    "pythia-125m": "EleutherAI/pythia-160m",
    "pythia-125m-deduped": "EleutherAI/pythia-160m-deduped",
    "pythia-125m-deduped-v0": "EleutherAI/pythia-160m-deduped-v0",
    "pythia-125m-seed1": "EleutherAI/pythia-160m-seed1",
    "pythia-125m-seed2": "EleutherAI/pythia-160m-seed2",
    "pythia-125m-seed3": "EleutherAI/pythia-160m-seed3",
    "pythia-125m-v0": "EleutherAI/pythia-160m-v0",
    "pythia-12b": "EleutherAI/pythia-12b",
    "pythia-12b-deduped": "EleutherAI/pythia-12b-deduped",
    "pythia-12b-deduped-v0": "EleutherAI/pythia-12b-deduped-v0",
    "pythia-12b-v0": "EleutherAI/pythia-12b-v0",
    "pythia-13b": "EleutherAI/pythia-12b",
    "pythia-13b-deduped": "EleutherAI/pythia-12b-deduped",
    "pythia-13b-deduped-v0": "EleutherAI/pythia-12b-deduped-v0",
    "pythia-13b-v0": "EleutherAI/pythia-12b-v0",
    "pythia-14m": "EleutherAI/pythia-14m",
    "pythia-160m": "EleutherAI/pythia-160m",
    "pythia-160m-deduped": "EleutherAI/pythia-160m-deduped",
    "pythia-160m-deduped-v0": "EleutherAI/pythia-160m-deduped-v0",
    "pythia-160m-seed1": "EleutherAI/pythia-160m-seed1",
    "pythia-160m-seed2": "EleutherAI/pythia-160m-seed2",
    "pythia-160m-seed3": "EleutherAI/pythia-160m-seed3",
    "pythia-160m-v0": "EleutherAI/pythia-160m-v0",
    "pythia-19m": "EleutherAI/pythia-70m",
    "pythia-19m-deduped": "EleutherAI/pythia-70m-deduped",
    "pythia-19m-deduped-v0": "EleutherAI/pythia-70m-deduped-v0",
    "pythia-19m-v0": "EleutherAI/pythia-70m-v0",
    "pythia-1b": "EleutherAI/pythia-1b",
    "pythia-1b-deduped": "EleutherAI/pythia-1b-deduped",
    "pythia-1b-deduped-v0": "EleutherAI/pythia-1b-deduped-v0",
    "pythia-1b-v0": "EleutherAI/pythia-1b-v0",
    "pythia-2.7b": "EleutherAI/pythia-2.8b",
    "pythia-2.7b-deduped": "EleutherAI/pythia-2.8b-deduped",
    "pythia-2.7b-deduped-v0": "EleutherAI/pythia-2.8b-deduped-v0",
    "pythia-2.7b-v0": "EleutherAI/pythia-2.8b-v0",
    "pythia-2.8b": "EleutherAI/pythia-2.8b",
    "pythia-2.8b-deduped": "EleutherAI/pythia-2.8b-deduped",
    "pythia-2.8b-deduped-v0": "EleutherAI/pythia-2.8b-deduped-v0",
    "pythia-2.8b-v0": "EleutherAI/pythia-2.8b-v0",
    "pythia-31m": "EleutherAI/pythia-31m",
    "pythia-350m": "EleutherAI/pythia-410m",
    "pythia-350m-deduped": "EleutherAI/pythia-410m-deduped",
    "pythia-350m-deduped-v0": "EleutherAI/pythia-410m-deduped-v0",
    "pythia-350m-v0": "EleutherAI/pythia-410m-v0",
    "pythia-410m": "EleutherAI/pythia-410m",
    "pythia-410m-deduped": "EleutherAI/pythia-410m-deduped",
    "pythia-410m-deduped-v0": "EleutherAI/pythia-410m-deduped-v0",
    "pythia-410m-v0": "EleutherAI/pythia-410m-v0",
    "pythia-6.7b": "EleutherAI/pythia-6.9b",
    "pythia-6.7b-deduped": "EleutherAI/pythia-6.9b-deduped",
    "pythia-6.7b-deduped-v0": "EleutherAI/pythia-6.9b-deduped-v0",
    "pythia-6.7b-v0": "EleutherAI/pythia-6.9b-v0",
    "pythia-6.9b": "EleutherAI/pythia-6.9b",
    "pythia-6.9b-deduped": "EleutherAI/pythia-6.9b-deduped",
    "pythia-6.9b-deduped-v0": "EleutherAI/pythia-6.9b-deduped-v0",
    "pythia-6.9b-v0": "EleutherAI/pythia-6.9b-v0",
    "pythia-70m": "EleutherAI/pythia-70m",
    "pythia-70m-deduped": "EleutherAI/pythia-70m-deduped",
    "pythia-70m-deduped-v0": "EleutherAI/pythia-70m-deduped-v0",
    "pythia-70m-v0": "EleutherAI/pythia-70m-v0",
    "pythia-800m": "EleutherAI/pythia-1b",
    "pythia-800m-deduped": "EleutherAI/pythia-1b-deduped",
    "pythia-800m-deduped-v0": "EleutherAI/pythia-1b-deduped-v0",
    "pythia-800m-v0": "EleutherAI/pythia-1b-v0",
    "pythia-v0": "EleutherAI/pythia-70m-v0",
    "qwen-1.8b": "Qwen/Qwen-1_8B",
    "qwen-1.8b-chat": "Qwen/Qwen-1_8B-Chat",
    "qwen-14b": "Qwen/Qwen-14B",
    "qwen-14b-chat": "Qwen/Qwen-14B-Chat",
    "qwen-32b-preview": "Qwen/QwQ-32B-Preview",
    "qwen-7b": "Qwen/Qwen-7B",
    "qwen-7b-chat": "Qwen/Qwen-7B-Chat",
    "qwen/qwen-14b": "Qwen/Qwen-14B",
    "qwen/qwen-14b-chat": "Qwen/Qwen-14B-Chat",
    "qwen/qwen-1_8b": "Qwen/Qwen-1_8B",
    "qwen/qwen-1_8b-chat": "Qwen/Qwen-1_8B-Chat",
    "qwen/qwen-7b": "Qwen/Qwen-7B",
    "qwen/qwen-7b-chat": "Qwen/Qwen-7B-Chat",
    "qwen/qwen1.5-0.5b": "Qwen/Qwen1.5-0.5B",
    "qwen/qwen1.5-0.5b-chat": "Qwen/Qwen1.5-0.5B-Chat",
    "qwen/qwen1.5-1.8b": "Qwen/Qwen1.5-1.8B",
    "qwen/qwen1.5-1.8b-chat": "Qwen/Qwen1.5-1.8B-Chat",
    "qwen/qwen1.5-14b": "Qwen/Qwen1.5-14B",
    "qwen/qwen1.5-14b-chat": "Qwen/Qwen1.5-14B-Chat",
    "qwen/qwen1.5-4b": "Qwen/Qwen1.5-4B",
    "qwen/qwen1.5-4b-chat": "Qwen/Qwen1.5-4B-Chat",
    "qwen/qwen1.5-7b": "Qwen/Qwen1.5-7B",
    "qwen/qwen1.5-7b-chat": "Qwen/Qwen1.5-7B-Chat",
    "qwen/qwen2-0.5b": "Qwen/Qwen2-0.5B",
    "qwen/qwen2-0.5b-instruct": "Qwen/Qwen2-0.5B-Instruct",
    "qwen/qwen2-1.5b": "Qwen/Qwen2-1.5B",
    "qwen/qwen2-1.5b-instruct": "Qwen/Qwen2-1.5B-Instruct",
    "qwen/qwen2-7b": "Qwen/Qwen2-7B",
    "qwen/qwen2-7b-instruct": "Qwen/Qwen2-7B-Instruct",
    "qwen/qwen2.5-0.5b": "Qwen/Qwen2.5-0.5B",
    "qwen/qwen2.5-0.5b-instruct": "Qwen/Qwen2.5-0.5B-Instruct",
    "qwen/qwen2.5-1.5b": "Qwen/Qwen2.5-1.5B",
    "qwen/qwen2.5-1.5b-instruct": "Qwen/Qwen2.5-1.5B-Instruct",
    "qwen/qwen2.5-14b": "Qwen/Qwen2.5-14B",
    "qwen/qwen2.5-14b-instruct": "Qwen/Qwen2.5-14B-Instruct",
    "qwen/qwen2.5-32b": "Qwen/Qwen2.5-32B",
    "qwen/qwen2.5-32b-instruct": "Qwen/Qwen2.5-32B-Instruct",
    "qwen/qwen2.5-3b": "Qwen/Qwen2.5-3B",
    "qwen/qwen2.5-3b-instruct": "Qwen/Qwen2.5-3B-Instruct",
    "qwen/qwen2.5-72b": "Qwen/Qwen2.5-72B",
    "qwen/qwen2.5-72b-instruct": "Qwen/Qwen2.5-72B-Instruct",
    "qwen/qwen2.5-7b": "Qwen/Qwen2.5-7B",
    "qwen/qwen2.5-7b-instruct": "Qwen/Qwen2.5-7B-Instruct",
    "qwen/qwen3-0.6b": "Qwen/Qwen3-0.6B",
    "qwen/qwen3-0.6b-base": "Qwen/Qwen3-0.6B-Base",
    "qwen/qwen3-1.7b": "Qwen/Qwen3-1.7B",
    "qwen/qwen3-14b": "Qwen/Qwen3-14B",
    "qwen/qwen3-4b": "Qwen/Qwen3-4B",
    "qwen/qwen3-8b": "Qwen/Qwen3-8B",
    "qwen/qwq-32b-preview": "Qwen/QwQ-32B-Preview",
    "qwen1.5-0.5b": "Qwen/Qwen1.5-0.5B",
    "qwen1.5-0.5b-chat": "Qwen/Qwen1.5-0.5B-Chat",
    "qwen1.5-1.8b": "Qwen/Qwen1.5-1.8B",
    "qwen1.5-1.8b-chat": "Qwen/Qwen1.5-1.8B-Chat",
    "qwen1.5-14b": "Qwen/Qwen1.5-14B",
    "qwen1.5-14b-chat": "Qwen/Qwen1.5-14B-Chat",
    "qwen1.5-4b": "Qwen/Qwen1.5-4B",
    "qwen1.5-4b-chat": "Qwen/Qwen1.5-4B-Chat",
    "qwen1.5-7b": "Qwen/Qwen1.5-7B",
    "qwen1.5-7b-chat": "Qwen/Qwen1.5-7B-Chat",
    "qwen2-0.5b": "Qwen/Qwen2-0.5B",
    "qwen2-0.5b-instruct": "Qwen/Qwen2-0.5B-Instruct",
    "qwen2-1.5b": "Qwen/Qwen2-1.5B",
    "qwen2-1.5b-instruct": "Qwen/Qwen2-1.5B-Instruct",
    "qwen2-7b": "Qwen/Qwen2-7B",
    "qwen2-7b-instruct": "Qwen/Qwen2-7B-Instruct",
    "qwen2.5-0.5b": "Qwen/Qwen2.5-0.5B",
    "qwen2.5-0.5b-instruct": "Qwen/Qwen2.5-0.5B-Instruct",
    "qwen2.5-1.5b": "Qwen/Qwen2.5-1.5B",
    "qwen2.5-1.5b-instruct": "Qwen/Qwen2.5-1.5B-Instruct",
    "qwen2.5-14b": "Qwen/Qwen2.5-14B",
    "qwen2.5-14b-instruct": "Qwen/Qwen2.5-14B-Instruct",
    "qwen2.5-32b": "Qwen/Qwen2.5-32B",
    "qwen2.5-32b-instruct": "Qwen/Qwen2.5-32B-Instruct",
    "qwen2.5-3b": "Qwen/Qwen2.5-3B",
    "qwen2.5-3b-instruct": "Qwen/Qwen2.5-3B-Instruct",
    "qwen2.5-72b": "Qwen/Qwen2.5-72B",
    "qwen2.5-72b-instruct": "Qwen/Qwen2.5-72B-Instruct",
    "qwen2.5-7b": "Qwen/Qwen2.5-7B",
    "qwen2.5-7b-instruct": "Qwen/Qwen2.5-7B-Instruct",
    "qwen3-0.6b": "Qwen/Qwen3-0.6B",
    "qwen3-0.6b-base": "Qwen/Qwen3-0.6B-Base",
    "qwen3-1.7b": "Qwen/Qwen3-1.7B",
    "qwen3-14b": "Qwen/Qwen3-14B",
    "qwen3-4b": "Qwen/Qwen3-4B",
    "qwen3-8b": "Qwen/Qwen3-8B",
    "redwood_attn_2l": "ArthurConmy/redwood_attn_2l",
    "roneneldan/tinystories-1layer-21m": "roneneldan/TinyStories-1Layer-21M",
    "roneneldan/tinystories-1m": "roneneldan/TinyStories-1M",
    "roneneldan/tinystories-28m": "roneneldan/TinyStories-28M",
    "roneneldan/tinystories-2layers-33m": "roneneldan/TinyStories-2Layers-33M",
    "roneneldan/tinystories-33m": "roneneldan/TinyStories-33M",
    "roneneldan/tinystories-3m": "roneneldan/TinyStories-3M",
    "roneneldan/tinystories-8m": "roneneldan/TinyStories-8M",
    "roneneldan/tinystories-instruct-1m": "roneneldan/TinyStories-Instruct-1M",
    "roneneldan/tinystories-instruct-28m": "roneneldan/TinyStories-Instruct-28M",
    "roneneldan/tinystories-instruct-2layers-33m": "roneneldan/TinyStories-Instruct-2Layers-33M",
    "roneneldan/tinystories-instruct-33m": "roneneldan/TinyStories-Instruct-33M",
    "roneneldan/tinystories-instruct-3m": "roneneldan/TinyStories-Instruct-3M",
    "roneneldan/tinystories-instruct-8m": "roneneldan/TinyStories-Instruct-8M",
    "roneneldan/tinystories-instuct-1layer-21m": "roneneldan/TinyStories-Instuct-1Layer-21M",
    "santacoder": "bigcode/santacoder",
    "solu-10l": "NeelNanda/SoLU_10L1280W_C4_Code",
    "solu-10l-c4-code": "NeelNanda/SoLU_10L1280W_C4_Code",
    "solu-10l-new": "NeelNanda/SoLU_10L1280W_C4_Code",
    "solu-10l-old": "NeelNanda/SoLU_10L_v22_old",
    "solu-10l-pile": "NeelNanda/SoLU_10L_v22_old",
    "solu-12l": "NeelNanda/SoLU_12L1536W_C4_Code",
    "solu-12l-c4-code": "NeelNanda/SoLU_12L1536W_C4_Code",
    "solu-12l-new": "NeelNanda/SoLU_12L1536W_C4_Code",
    "solu-12l-old": "NeelNanda/SoLU_12L_v23_old",
    "solu-12l-pile": "NeelNanda/SoLU_12L_v23_old",
    "solu-1l": "NeelNanda/SoLU_1L512W_C4_Code",
    "solu-1l-c4-code": "NeelNanda/SoLU_1L512W_C4_Code",
    "solu-1l-finetune": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "solu-1l-new": "NeelNanda/SoLU_1L512W_C4_Code",
    "solu-1l-old": "NeelNanda/SoLU_1L_v9_old",
    "solu-1l-pile": "NeelNanda/SoLU_1L_v9_old",
    "solu-1l-wiki": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "solu-1l-wiki-finetune": "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "solu-2l": "NeelNanda/SoLU_2L512W_C4_Code",
    "solu-2l-c4-code": "NeelNanda/SoLU_2L512W_C4_Code",
    "solu-2l-new": "NeelNanda/SoLU_2L512W_C4_Code",
    "solu-2l-old": "NeelNanda/SoLU_2L_v10_old",
    "solu-2l-pile": "NeelNanda/SoLU_2L_v10_old",
    "solu-3l": "NeelNanda/SoLU_3L512W_C4_Code",
    "solu-3l-c4-code": "NeelNanda/SoLU_3L512W_C4_Code",
    "solu-3l-new": "NeelNanda/SoLU_3L512W_C4_Code",
    "solu-4l": "NeelNanda/SoLU_4L512W_C4_Code",
    "solu-4l-c4-code": "NeelNanda/SoLU_4L512W_C4_Code",
    "solu-4l-finetune": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "solu-4l-new": "NeelNanda/SoLU_4L512W_C4_Code",
    "solu-4l-old": "NeelNanda/SoLU_4L_v11_old",
    "solu-4l-pile": "NeelNanda/SoLU_4L_v11_old",
    "solu-4l-wiki": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "solu-4l-wiki-finetune": "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "solu-6l": "NeelNanda/SoLU_6L768W_C4_Code",
    "solu-6l-c4-code": "NeelNanda/SoLU_6L768W_C4_Code",
    "solu-6l-new": "NeelNanda/SoLU_6L768W_C4_Code",
    "solu-6l-old": "NeelNanda/SoLU_6L_v13_old",
    "solu-6l-pile": "NeelNanda/SoLU_6L_v13_old",
    "solu-8l": "NeelNanda/SoLU_8L1024W_C4_Code",
    "solu-8l-c4-code": "NeelNanda/SoLU_8L1024W_C4_Code",
    "solu-8l-new": "NeelNanda/SoLU_8L1024W_C4_Code",
    "solu-8l-old": "NeelNanda/SoLU_8L_v21_old",
    "solu-8l-pile": "NeelNanda/SoLU_8L_v21_old",
    "stabilityai/stablelm-base-alpha-3b": "stabilityai/stablelm-base-alpha-3b",
    "stabilityai/stablelm-base-alpha-7b": "stabilityai/stablelm-base-alpha-7b",
    "stabilityai/stablelm-tuned-alpha-3b": "stabilityai/stablelm-tuned-alpha-3b",
    "stabilityai/stablelm-tuned-alpha-7b": "stabilityai/stablelm-tuned-alpha-7b",
    "stablelm-base-3b": "stabilityai/stablelm-base-alpha-3b",
    "stablelm-base-7b": "stabilityai/stablelm-base-alpha-7b",
    "stablelm-base-alpha-3b": "stabilityai/stablelm-base-alpha-3b",
    "stablelm-base-alpha-7b": "stabilityai/stablelm-base-alpha-7b",
    "stablelm-tuned-3b": "stabilityai/stablelm-tuned-alpha-3b",
    "stablelm-tuned-7b": "stabilityai/stablelm-tuned-alpha-7b",
    "stablelm-tuned-alpha-3b": "stabilityai/stablelm-tuned-alpha-3b",
    "stablelm-tuned-alpha-7b": "stabilityai/stablelm-tuned-alpha-7b",
    "stanford-crfm/alias-gpt2-small-x21": "stanford-crfm/alias-gpt2-small-x21",
    "stanford-crfm/arwen-gpt2-medium-x21": "stanford-crfm/arwen-gpt2-medium-x21",
    "stanford-crfm/battlestar-gpt2-small-x49": "stanford-crfm/battlestar-gpt2-small-x49",
    "stanford-crfm/beren-gpt2-medium-x49": "stanford-crfm/beren-gpt2-medium-x49",
    "stanford-crfm/caprica-gpt2-small-x81": "stanford-crfm/caprica-gpt2-small-x81",
    "stanford-crfm/celebrimbor-gpt2-medium-x81": "stanford-crfm/celebrimbor-gpt2-medium-x81",
    "stanford-crfm/darkmatter-gpt2-small-x343": "stanford-crfm/darkmatter-gpt2-small-x343",
    "stanford-crfm/durin-gpt2-medium-x343": "stanford-crfm/durin-gpt2-medium-x343",
    "stanford-crfm/eowyn-gpt2-medium-x777": "stanford-crfm/eowyn-gpt2-medium-x777",
    "stanford-crfm/expanse-gpt2-small-x777": "stanford-crfm/expanse-gpt2-small-x777",
    "stanford-gpt2-medium-a": "stanford-crfm/arwen-gpt2-medium-x21",
    "stanford-gpt2-medium-b": "stanford-crfm/beren-gpt2-medium-x49",
    "stanford-gpt2-medium-c": "stanford-crfm/celebrimbor-gpt2-medium-x81",
    "stanford-gpt2-medium-d": "stanford-crfm/durin-gpt2-medium-x343",
    "stanford-gpt2-medium-e": "stanford-crfm/eowyn-gpt2-medium-x777",
    "stanford-gpt2-small-a": "stanford-crfm/alias-gpt2-small-x21",
    "stanford-gpt2-small-b": "stanford-crfm/battlestar-gpt2-small-x49",
    "stanford-gpt2-small-c": "stanford-crfm/caprica-gpt2-small-x81",
    "stanford-gpt2-small-d": "stanford-crfm/darkmatter-gpt2-small-x343",
    "stanford-gpt2-small-e": "stanford-crfm/expanse-gpt2-small-x777",
    "swiss-ai/apertus-8b-2509": "swiss-ai/Apertus-8B-2509",
    "swiss-ai/apertus-8b-instruct-2509": "swiss-ai/Apertus-8B-Instruct-2509",
    "t5-base": "google-t5/t5-base",
    "t5-large": "google-t5/t5-large",
    "t5-small": "google-t5/t5-small",
    "tiny-stories-1l-21m": "roneneldan/TinyStories-1Layer-21M",
    "tiny-stories-1m": "roneneldan/TinyStories-1M",
    "tiny-stories-28m": "roneneldan/TinyStories-28M",
    "tiny-stories-2l-33m": "roneneldan/TinyStories-2Layers-33M",
    "tiny-stories-33m": "roneneldan/TinyStories-33M",
    "tiny-stories-3m": "roneneldan/TinyStories-3M",
    "tiny-stories-8m": "roneneldan/TinyStories-8M",
    "tiny-stories-instruct-1l-21m": "roneneldan/TinyStories-Instuct-1Layer-21M",
    "tiny-stories-instruct-1m": "roneneldan/TinyStories-Instruct-1M",
    "tiny-stories-instruct-28m": "roneneldan/TinyStories-Instruct-28M",
    "tiny-stories-instruct-2l-33m": "roneneldan/TinyStories-Instruct-2Layers-33M",
    "tiny-stories-instruct-33m": "roneneldan/TinyStories-Instruct-33M",
    "tiny-stories-instruct-3m": "roneneldan/TinyStories-Instruct-3M",
    "tiny-stories-instruct-8m": "roneneldan/TinyStories-Instruct-8M",
    "w2v2-base": "facebook/wav2vec2-base",
    "w2v2-large": "facebook/wav2vec2-large",
    "wav2vec2-base": "facebook/wav2vec2-base",
    "wav2vec2-large": "facebook/wav2vec2-large",
    "yi-34b": "01-ai/Yi-34B",
    "yi-34b-chat": "01-ai/Yi-34B-Chat",
    "yi-6b": "01-ai/Yi-6B",
    "yi-6b-chat": "01-ai/Yi-6B-Chat",
}

TRANSFORMER_LENS_SAFE_LENS_MODEL_ALIASES: dict[str, str] = {
    "distilbert-base-uncased": "distilbert/distilbert-base-uncased",
    "gpt-neo": "EleutherAI/gpt-neo-125M",
    "llama-13b": "huggyllama/llama-13b",
    "llama-13b-hf": "huggyllama/llama-13b",
    "llama-30b": "huggyllama/llama-30b",
    "llama-30b-hf": "huggyllama/llama-30b",
    "llama-65b": "huggyllama/llama-65b",
    "llama-65b-hf": "huggyllama/llama-65b",
    "llama-7b": "huggyllama/llama-7b",
    "llama-7b-hf": "huggyllama/llama-7b",
    "roberta-base": "FacebookAI/roberta-base",
}

TRANSFORMER_LENS_BRIDGE_MODEL_ALIASES: dict[str, str] = {
    "mamba-130m": "state-spaces/mamba-130m-hf",
    "mamba-370m": "state-spaces/mamba-370m-hf",
    "mamba-790m": "state-spaces/mamba-790m-hf",
    "mamba-1.4b": "state-spaces/mamba-1.4b-hf",
    "mamba-2.8b": "state-spaces/mamba-2.8b-hf",
    "mamba-codestral": "mistralai/Mamba-Codestral-7B-v0.1",
    "mamba-codestral-7b": "mistralai/Mamba-Codestral-7B-v0.1",
    "mistralai/mamba-codestral-7b-v0.1": "mistralai/Mamba-Codestral-7B-v0.1",
    "qwen/qwen2-57b-a14b": "Qwen/Qwen2-57B-A14B",
    "qwen/qwen3-30b-a3b": "Qwen/Qwen3-30B-A3B",
    "qwen/qwen3-235b-a22b": "Qwen/Qwen3-235B-A22B",
    "qwen2-57b-a14b": "Qwen/Qwen2-57B-A14B",
    "qwen3-30b-a3b": "Qwen/Qwen3-30B-A3B",
    "qwen3-235b-a22b": "Qwen/Qwen3-235B-A22B",
    "state-spaces/mamba-130m": "state-spaces/mamba-130m",
    "state-spaces/mamba-130m-hf": "state-spaces/mamba-130m-hf",
    "state-spaces/mamba-370m-hf": "state-spaces/mamba-370m-hf",
    "state-spaces/mamba-790m-hf": "state-spaces/mamba-790m-hf",
    "state-spaces/mamba-1.4b-hf": "state-spaces/mamba-1.4b-hf",
    "state-spaces/mamba-2.8b-hf": "state-spaces/mamba-2.8b-hf",
}

TRANSFORMER_LENS_COMPATIBLE_MODEL_ALIASES: dict[str, str] = {
    **TRANSFORMER_LENS_OFFICIAL_MODEL_ALIASES,
    **TRANSFORMER_LENS_SAFE_LENS_MODEL_ALIASES,
    **TRANSFORMER_LENS_BRIDGE_MODEL_ALIASES,
    **TRANSFORMER_LENS_NATIVE_CHECKPOINT_ALIASES,
}

_TRANSFORMER_LENS_NATIVE_CHECKPOINT_MARKERS = (
    "neelnanda/",
    "arthurconmy/redwood_attn_2l",
    "baidicoot/othello-gpt-transformer-lens",
)
_TRANSFORMER_LENS_NATIVE_CHECKPOINT_NAMES = frozenset(
    name.lower()
    for name in TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES
    if any(marker in name.lower() for marker in _TRANSFORMER_LENS_NATIVE_CHECKPOINT_MARKERS)
)


def transformer_lens_official_model_names() -> list[str]:
    """Return the vendored TransformerLens-compatible official model names."""
    return list(TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES)


def resolve_transformer_lens_compatible_model_name(model_name: str) -> str:
    """Resolve common TransformerLens aliases to public Transformers IDs."""
    return TRANSFORMER_LENS_COMPATIBLE_MODEL_ALIASES.get(model_name.lower(), model_name)


def is_transformer_lens_native_checkpoint(model_name: str) -> bool:
    """Return whether a name resolves to a native HookedTransformer checkpoint repo."""
    resolved = resolve_transformer_lens_compatible_model_name(model_name)
    lowered_values = (model_name.lower(), resolved.lower())
    return any(lowered in _TRANSFORMER_LENS_NATIVE_CHECKPOINT_NAMES for lowered in lowered_values)


def is_transformer_lens_official_model_name(model_name: str) -> bool:
    """Return whether a model name or alias resolves to the vendored official list."""
    lowered = model_name.lower()
    official = {name.lower() for name in TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES}
    official_alias = TRANSFORMER_LENS_OFFICIAL_MODEL_ALIASES.get(lowered)
    return (
        lowered in official
        or official_alias is not None
        and official_alias.lower() in official
    )


def is_transformer_lens_supported_model_name(model_name: str) -> bool:
    """Return whether a model name or common alias is in the compatibility table."""
    lowered = model_name.lower()
    official = {name.lower() for name in TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES}
    aliases = {name.lower() for name in TRANSFORMER_LENS_COMMON_ALIASES}
    compatible_aliases = {
        name.lower() for name in TRANSFORMER_LENS_COMPATIBLE_MODEL_ALIASES
    }
    return (
        lowered in official
        or lowered in aliases
        or lowered in compatible_aliases
    )


def transformer_lens_model_kind(model_name: str) -> str:
    """Return the SafeLens compatibility family needed for a model."""
    lowered = resolve_transformer_lens_compatible_model_name(model_name).lower()
    if "wav2vec2" in lowered or "hubert" in lowered:
        return "audio_encoder"
    if lowered == "t5" or "t5-" in lowered or "google-t5/" in lowered:
        return "encoder_decoder"
    if lowered in {"bert", "roberta", "distilbert"} or any(
        marker in lowered for marker in ("bert-", "google-bert/", "roberta", "distilbert")
    ):
        return "encoder"
    return "decoder"
