"""TransformerLens model coverage metadata.

The official names below mirror TransformerLens' `supported_models.py` list
consulted on 2026-05-14. SafeLens uses them for static inspection and adapter
selection. Runtime loading stays inside SafeLens' own Transformers-based
wrappers; this module is a compatibility target, not a dependency bridge.
"""

from __future__ import annotations

TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES: tuple[str, ...] = (
    "01-ai/Yi-34B",
    "01-ai/Yi-34B-Chat",
    "01-ai/Yi-6B",
    "01-ai/Yi-6B-Chat",
    "ai-forever/mGPT",
    "allenai/OLMo-1B-hf",
    "allenai/OLMo-2-0425-1B",
    "allenai/OLMo-2-1124-7B",
    "allenai/Olmo-3-32B-Think",
    "allenai/Olmo-3-7B-Instruct",
    "allenai/Olmo-3-7B-Think",
    "allenai/Olmo-3.1-32B-Instruct",
    "allenai/Olmo-3.1-32B-Think",
    "allenai/OLMo-7B-hf",
    "allenai/OLMoE-1B-7B-0924",
    "ArthurConmy/redwood_attn_2l",
    "Baidicoot/Othello-GPT-Transformer-Lens",
    "bigcode/santacoder",
    "bigscience/bloom-1b1",
    "bigscience/bloom-1b7",
    "bigscience/bloom-3b",
    "bigscience/bloom-560m",
    "bigscience/bloom-7b1",
    "codellama/CodeLlama-7b-hf",
    "codellama/CodeLlama-7b-Instruct-hf",
    "codellama/CodeLlama-7b-Python-hf",
    "distilgpt2",
    "EleutherAI/gpt-j-6B",
    "EleutherAI/gpt-neo-1.3B",
    "EleutherAI/gpt-neo-125M",
    "EleutherAI/gpt-neo-2.7B",
    "EleutherAI/gpt-neox-20b",
    "EleutherAI/pythia-1.4b",
    "EleutherAI/pythia-1.4b-deduped",
    "EleutherAI/pythia-1.4b-deduped-v0",
    "EleutherAI/pythia-1.4b-v0",
    "EleutherAI/pythia-12b",
    "EleutherAI/pythia-12b-deduped",
    "EleutherAI/pythia-12b-deduped-v0",
    "EleutherAI/pythia-12b-v0",
    "EleutherAI/pythia-14m",
    "EleutherAI/pythia-160m",
    "EleutherAI/pythia-160m-deduped",
    "EleutherAI/pythia-160m-deduped-v0",
    "EleutherAI/pythia-160m-seed1",
    "EleutherAI/pythia-160m-seed2",
    "EleutherAI/pythia-160m-seed3",
    "EleutherAI/pythia-160m-v0",
    "EleutherAI/pythia-1b",
    "EleutherAI/pythia-1b-deduped",
    "EleutherAI/pythia-1b-deduped-v0",
    "EleutherAI/pythia-1b-v0",
    "EleutherAI/pythia-2.8b",
    "EleutherAI/pythia-2.8b-deduped",
    "EleutherAI/pythia-2.8b-deduped-v0",
    "EleutherAI/pythia-2.8b-v0",
    "EleutherAI/pythia-31m",
    "EleutherAI/pythia-410m",
    "EleutherAI/pythia-410m-deduped",
    "EleutherAI/pythia-410m-deduped-v0",
    "EleutherAI/pythia-410m-v0",
    "EleutherAI/pythia-6.9b",
    "EleutherAI/pythia-6.9b-deduped",
    "EleutherAI/pythia-6.9b-deduped-v0",
    "EleutherAI/pythia-6.9b-v0",
    "EleutherAI/pythia-70m",
    "EleutherAI/pythia-70m-deduped",
    "EleutherAI/pythia-70m-deduped-v0",
    "EleutherAI/pythia-70m-v0",
    "facebook/hubert-base-ls960",
    "facebook/opt-1.3b",
    "facebook/opt-125m",
    "facebook/opt-13b",
    "facebook/opt-2.7b",
    "facebook/opt-30b",
    "facebook/opt-6.7b",
    "facebook/opt-66b",
    "facebook/wav2vec2-base",
    "facebook/wav2vec2-large",
    "google-bert/bert-base-cased",
    "google-bert/bert-base-uncased",
    "google-bert/bert-large-cased",
    "google-bert/bert-large-uncased",
    "google-t5/t5-base",
    "google-t5/t5-large",
    "google-t5/t5-small",
    "google/gemma-2-27b",
    "google/gemma-2-27b-it",
    "google/gemma-2-2b",
    "google/gemma-2-2b-it",
    "google/gemma-2-9b",
    "google/gemma-2-9b-it",
    "google/gemma-2b",
    "google/gemma-2b-it",
    "google/gemma-3-12b-it",
    "google/gemma-3-12b-pt",
    "google/gemma-3-1b-it",
    "google/gemma-3-1b-pt",
    "google/gemma-3-270m",
    "google/gemma-3-270m-it",
    "google/gemma-3-27b-it",
    "google/gemma-3-27b-pt",
    "google/gemma-3-4b-it",
    "google/gemma-3-4b-pt",
    "google/gemma-7b",
    "google/gemma-7b-it",
    "google/medgemma-27b-it",
    "google/medgemma-27b-text-it",
    "google/medgemma-4b-it",
    "google/medgemma-4b-pt",
    "gpt2",
    "gpt2-large",
    "gpt2-medium",
    "gpt2-xl",
    "llama-13b-hf",
    "llama-30b-hf",
    "llama-65b-hf",
    "llama-7b-hf",
    "meta-llama/Llama-2-13b-chat-hf",
    "meta-llama/Llama-2-13b-hf",
    "meta-llama/Llama-2-70b-chat-hf",
    "meta-llama/Llama-2-7b-chat-hf",
    "meta-llama/Llama-2-7b-hf",
    "meta-llama/Llama-3.1-70B",
    "meta-llama/Llama-3.1-70B-Instruct",
    "meta-llama/Llama-3.1-8B",
    "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.2-1B",
    "meta-llama/Llama-3.2-1B-Instruct",
    "meta-llama/Llama-3.2-3B",
    "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct",
    "meta-llama/Meta-Llama-3-70B",
    "meta-llama/Meta-Llama-3-70B-Instruct",
    "meta-llama/Meta-Llama-3-8B",
    "meta-llama/Meta-Llama-3-8B-Instruct",
    "microsoft/phi-1",
    "microsoft/phi-1_5",
    "microsoft/phi-2",
    "microsoft/Phi-3-mini-4k-instruct",
    "microsoft/phi-4",
    "mistralai/Mistral-7B-Instruct-v0.1",
    "mistralai/Mistral-7B-v0.1",
    "mistralai/Mistral-Nemo-Base-2407",
    "mistralai/Mistral-Small-24B-Base-2501",
    "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "mistralai/Mixtral-8x7B-v0.1",
    "NeelNanda/Attn-Only-2L512W-Shortformer-6B-big-lr",
    "NeelNanda/Attn_Only_1L512W_C4_Code",
    "NeelNanda/Attn_Only_2L512W_C4_Code",
    "NeelNanda/Attn_Only_3L512W_C4_Code",
    "NeelNanda/Attn_Only_4L512W_C4_Code",
    "NeelNanda/GELU_1L512W_C4_Code",
    "NeelNanda/GELU_2L512W_C4_Code",
    "NeelNanda/GELU_3L512W_C4_Code",
    "NeelNanda/GELU_4L512W_C4_Code",
    "NeelNanda/SoLU_10L1280W_C4_Code",
    "NeelNanda/SoLU_10L_v22_old",
    "NeelNanda/SoLU_12L1536W_C4_Code",
    "NeelNanda/SoLU_12L_v23_old",
    "NeelNanda/SoLU_1L512W_C4_Code",
    "NeelNanda/SoLU_1L512W_Wiki_Finetune",
    "NeelNanda/SoLU_1L_v9_old",
    "NeelNanda/SoLU_2L512W_C4_Code",
    "NeelNanda/SoLU_2L_v10_old",
    "NeelNanda/SoLU_3L512W_C4_Code",
    "NeelNanda/SoLU_4L512W_C4_Code",
    "NeelNanda/SoLU_4L512W_Wiki_Finetune",
    "NeelNanda/SoLU_4L_v11_old",
    "NeelNanda/SoLU_6L768W_C4_Code",
    "NeelNanda/SoLU_6L_v13_old",
    "NeelNanda/SoLU_8L1024W_C4_Code",
    "NeelNanda/SoLU_8L_v21_old",
    "openai/gpt-oss-20b",
    "Qwen/Qwen-14B",
    "Qwen/Qwen-14B-Chat",
    "Qwen/Qwen-1_8B",
    "Qwen/Qwen-1_8B-Chat",
    "Qwen/Qwen-7B",
    "Qwen/Qwen-7B-Chat",
    "Qwen/Qwen1.5-0.5B",
    "Qwen/Qwen1.5-0.5B-Chat",
    "Qwen/Qwen1.5-1.8B",
    "Qwen/Qwen1.5-1.8B-Chat",
    "Qwen/Qwen1.5-14B",
    "Qwen/Qwen1.5-14B-Chat",
    "Qwen/Qwen1.5-4B",
    "Qwen/Qwen1.5-4B-Chat",
    "Qwen/Qwen1.5-7B",
    "Qwen/Qwen1.5-7B-Chat",
    "Qwen/Qwen2-0.5B",
    "Qwen/Qwen2-0.5B-Instruct",
    "Qwen/Qwen2-1.5B",
    "Qwen/Qwen2-1.5B-Instruct",
    "Qwen/Qwen2-7B",
    "Qwen/Qwen2-7B-Instruct",
    "Qwen/Qwen2.5-0.5B",
    "Qwen/Qwen2.5-0.5B-Instruct",
    "Qwen/Qwen2.5-1.5B",
    "Qwen/Qwen2.5-1.5B-Instruct",
    "Qwen/Qwen2.5-14B",
    "Qwen/Qwen2.5-14B-Instruct",
    "Qwen/Qwen2.5-32B",
    "Qwen/Qwen2.5-32B-Instruct",
    "Qwen/Qwen2.5-3B",
    "Qwen/Qwen2.5-3B-Instruct",
    "Qwen/Qwen2.5-72B",
    "Qwen/Qwen2.5-72B-Instruct",
    "Qwen/Qwen2.5-7B",
    "Qwen/Qwen2.5-7B-Instruct",
    "Qwen/Qwen3-0.6B",
    "Qwen/Qwen3-0.6B-Base",
    "Qwen/Qwen3-1.7B",
    "Qwen/Qwen3-14B",
    "Qwen/Qwen3-4B",
    "Qwen/Qwen3-8B",
    "Qwen/QwQ-32B-Preview",
    "roneneldan/TinyStories-1Layer-21M",
    "roneneldan/TinyStories-1M",
    "roneneldan/TinyStories-28M",
    "roneneldan/TinyStories-2Layers-33M",
    "roneneldan/TinyStories-33M",
    "roneneldan/TinyStories-3M",
    "roneneldan/TinyStories-8M",
    "roneneldan/TinyStories-Instruct-1M",
    "roneneldan/TinyStories-Instruct-28M",
    "roneneldan/TinyStories-Instruct-2Layers-33M",
    "roneneldan/TinyStories-Instruct-33M",
    "roneneldan/TinyStories-Instruct-3M",
    "roneneldan/TinyStories-Instruct-8M",
    "roneneldan/TinyStories-Instuct-1Layer-21M",
    "stabilityai/stablelm-base-alpha-3b",
    "stabilityai/stablelm-base-alpha-7b",
    "stabilityai/stablelm-tuned-alpha-3b",
    "stabilityai/stablelm-tuned-alpha-7b",
    "stanford-crfm/alias-gpt2-small-x21",
    "stanford-crfm/arwen-gpt2-medium-x21",
    "stanford-crfm/battlestar-gpt2-small-x49",
    "stanford-crfm/beren-gpt2-medium-x49",
    "stanford-crfm/caprica-gpt2-small-x81",
    "stanford-crfm/celebrimbor-gpt2-medium-x81",
    "stanford-crfm/darkmatter-gpt2-small-x343",
    "stanford-crfm/durin-gpt2-medium-x343",
    "stanford-crfm/eowyn-gpt2-medium-x777",
    "stanford-crfm/expanse-gpt2-small-x777",
    "swiss-ai/Apertus-8B-2509",
    "swiss-ai/Apertus-8B-Instruct-2509",
)

TRANSFORMER_LENS_COMMON_ALIASES: tuple[str, ...] = (
    "gpt2-small",
    "gpt2-xs",
    "gpt-j",
    "gptj",
    "gpt-neo",
    "gpt-neox",
    "neox",
    "pythia",
    "opt",
    "bloom-560m",
    "llama-7b",
    "llama-13b",
    "llama-30b",
    "llama-65b",
    "mistral-7b",
    "mixtral",
    "qwen3-8b",
    "qwen3-14b",
    "gemma-2b",
    "gemma-7b",
    "phi-2",
    "tiny-stories-1m",
    "solu-1l",
    "attn-only-2l",
    "bert-base-uncased",
    "roberta-base",
    "distilbert-base-uncased",
    "t5-small",
    "hubert-base-ls960",
    "wav2vec2-base",
)

TRANSFORMER_LENS_COMPATIBLE_MODEL_ALIASES: dict[str, str] = {
    "gpt2-small": "gpt2",
    "gpt2-xs": "distilgpt2",
    "gpt-j": "EleutherAI/gpt-j-6B",
    "gptj": "EleutherAI/gpt-j-6B",
    "gpt-neo": "EleutherAI/gpt-neo-125M",
    "gpt-neox": "EleutherAI/gpt-neox-20b",
    "neox": "EleutherAI/gpt-neox-20b",
    "pythia": "EleutherAI/pythia-70m",
    "opt": "facebook/opt-125m",
    "bloom-560m": "bigscience/bloom-560m",
    "llama-7b": "huggyllama/llama-7b",
    "llama-7b-hf": "huggyllama/llama-7b",
    "llama-13b": "huggyllama/llama-13b",
    "llama-13b-hf": "huggyllama/llama-13b",
    "mistral-7b": "mistralai/Mistral-7B-v0.1",
    "mixtral": "mistralai/Mixtral-8x7B-v0.1",
    "qwen3-8b": "Qwen/Qwen3-8B",
    "qwen3-14b": "Qwen/Qwen3-14B",
    "gemma-2b": "google/gemma-2b",
    "gemma-7b": "google/gemma-7b",
    "phi-2": "microsoft/phi-2",
    "tiny-stories-1m": "roneneldan/TinyStories-1M",
    "solu-1l": "NeelNanda/SoLU_1L512W_C4_Code",
    "attn-only-2l": "NeelNanda/Attn_Only_2L512W_C4_Code",
    "bert-base-uncased": "google-bert/bert-base-uncased",
    "roberta-base": "FacebookAI/roberta-base",
    "distilbert-base-uncased": "distilbert/distilbert-base-uncased",
    "t5-small": "google-t5/t5-small",
    "hubert-base-ls960": "facebook/hubert-base-ls960",
    "wav2vec2-base": "facebook/wav2vec2-base",
}

_TRANSFORMER_LENS_MARKERS = (
    "gpt2",
    "distilgpt2",
    "pythia",
    "gpt-neo",
    "gptneo",
    "gpt-j",
    "gptj",
    "gpt-neox",
    "gptneox",
    "opt-",
    "optforcausallm",
    "bloom",
    "llama",
    "codellama",
    "mistral",
    "mixtral",
    "qwen",
    "qwq",
    "gemma",
    "medgemma",
    "olmo",
    "olmoe",
    "phi-",
    "stablelm",
    "tinystories",
    "tiny-stories",
    "neelnanda/",
    "solu_",
    "attn_only",
    "stanford-crfm/",
    "redwood_attn",
    "othello-gpt",
    "bert-",
    "google-bert/",
    "roberta",
    "distilbert",
    "t5-",
    "google-t5/",
    "wav2vec2",
    "hubert",
    "mgpt",
    "santacoder",
    "gpt-oss",
    "apertus",
    "/yi-",
    "01-ai/yi",
)


def transformer_lens_official_model_names() -> list[str]:
    """Return the vendored TransformerLens-compatible official model names."""
    return list(TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES)


def resolve_transformer_lens_compatible_model_name(model_name: str) -> str:
    """Resolve common TransformerLens aliases to public Transformers IDs."""
    return TRANSFORMER_LENS_COMPATIBLE_MODEL_ALIASES.get(model_name.lower(), model_name)


def is_transformer_lens_supported_model_name(model_name: str) -> bool:
    """Return whether a model name or common alias is in the compatibility table."""
    lowered = model_name.lower()
    official = {name.lower() for name in TRANSFORMER_LENS_OFFICIAL_MODEL_NAMES}
    aliases = {name.lower() for name in TRANSFORMER_LENS_COMMON_ALIASES}
    return (
        lowered in official
        or lowered in aliases
        or any(marker in lowered for marker in _TRANSFORMER_LENS_MARKERS)
    )


def transformer_lens_model_kind(model_name: str) -> str:
    """Return the SafeLens compatibility family needed for a model."""
    lowered = model_name.lower()
    if "wav2vec2" in lowered or "hubert" in lowered:
        return "audio_encoder"
    if "t5-" in lowered or "google-t5/" in lowered:
        return "encoder_decoder"
    if any(marker in lowered for marker in ("bert-", "google-bert/", "roberta", "distilbert")):
        return "encoder"
    return "decoder"
